services:
  db:
    image: postgres:17.4
    restart: "no"
    volumes:
      - edgeos-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  prestart:
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_SERVER=db

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    environment:
      - POSTGRES_SERVER=db
    build:
      context: .
      dockerfile: backend/Dockerfile
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov

  adminer:
    image: adminer
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=pepa-linha-dark

  backoffice:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: .
      dockerfile: backoffice/Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development

  # MinIO for local S3-compatible storage
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Create default bucket and configure CORS on startup
  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/uploads --ignore-existing;
      mc anonymous set download myminio/uploads;
      exit 0;
      "

volumes:
  edgeos-db-data:
  minio-data:
