packages:
  - ai-service
  - backoffice
  - portal
  - e2e
  - packages/shared-form-ui
  - packages/shared-events
  - packages/checkout-core
  - packages/checkout-react
  - examples/custom-checkout

onlyBuiltDependencies:
  - '@swc/core'
