/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout/payments'
import { Route as LayoutAttendeesRouteImport } from './routes/_layout/attendees'
import { Route as LayoutTenantsIndexRouteImport } from './routes/_layout/tenants/index'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout/products/index'
import { Route as LayoutPopupsIndexRouteImport } from './routes/_layout/popups/index'
import { Route as LayoutHumansIndexRouteImport } from './routes/_layout/humans/index'
import { Route as LayoutGroupsIndexRouteImport } from './routes/_layout/groups/index'
import { Route as LayoutFormBuilderIndexRouteImport } from './routes/_layout/form-builder/index'
import { Route as LayoutCouponsIndexRouteImport } from './routes/_layout/coupons/index'
import { Route as LayoutApplicationsIndexRouteImport } from './routes/_layout/applications/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutTenantsNewRouteImport } from './routes/_layout/tenants/new'
import { Route as LayoutProductsNewRouteImport } from './routes/_layout/products/new'
import { Route as LayoutPopupsNewRouteImport } from './routes/_layout/popups/new'
import { Route as LayoutHumansNewRouteImport } from './routes/_layout/humans/new'
import { Route as LayoutGroupsNewRouteImport } from './routes/_layout/groups/new'
import { Route as LayoutFormBuilderNewRouteImport } from './routes/_layout/form-builder/new'
import { Route as LayoutCouponsNewRouteImport } from './routes/_layout/coupons/new'
import { Route as LayoutApplicationsNewRouteImport } from './routes/_layout/applications/new'
import { Route as LayoutAdminNewRouteImport } from './routes/_layout/admin/new'
import { Route as LayoutTenantsIdEditRouteImport } from './routes/_layout/tenants/$id.edit'
import { Route as LayoutProductsIdEditRouteImport } from './routes/_layout/products/$id.edit'
import { Route as LayoutPopupsIdEditRouteImport } from './routes/_layout/popups/$id.edit'
import { Route as LayoutHumansIdEditRouteImport } from './routes/_layout/humans/$id.edit'
import { Route as LayoutGroupsIdEditRouteImport } from './routes/_layout/groups/$id.edit'
import { Route as LayoutFormBuilderIdEditRouteImport } from './routes/_layout/form-builder/$id.edit'
import { Route as LayoutCouponsIdEditRouteImport } from './routes/_layout/coupons/$id.edit'
import { Route as LayoutAdminIdEditRouteImport } from './routes/_layout/admin/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendeesRoute = LayoutAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTenantsIndexRoute = LayoutTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIndexRoute = LayoutPopupsIndexRouteImport.update({
  id: '/popups/',
  path: '/popups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHumansIndexRoute = LayoutHumansIndexRouteImport.update({
  id: '/humans/',
  path: '/humans/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIndexRoute = LayoutGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderIndexRoute = LayoutFormBuilderIndexRouteImport.update({
  id: '/form-builder/',
  path: '/form-builder/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouponsIndexRoute = LayoutCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsIndexRoute = LayoutApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTenantsNewRoute = LayoutTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsNewRoute = LayoutProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsNewRoute = LayoutPopupsNewRouteImport.update({
  id: '/popups/new',
  path: '/popups/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHumansNewRoute = LayoutHumansNewRouteImport.update({
  id: '/humans/new',
  path: '/humans/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsNewRoute = LayoutGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderNewRoute = LayoutFormBuilderNewRouteImport.update({
  id: '/form-builder/new',
  path: '/form-builder/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouponsNewRoute = LayoutCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsNewRoute = LayoutApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminNewRoute = LayoutAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTenantsIdEditRoute = LayoutTenantsIdEditRouteImport.update({
  id: '/tenants/$id/edit',
  path: '/tenants/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsIdEditRoute = LayoutProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIdEditRoute = LayoutPopupsIdEditRouteImport.update({
  id: '/popups/$id/edit',
  path: '/popups/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHumansIdEditRoute = LayoutHumansIdEditRouteImport.update({
  id: '/humans/$id/edit',
  path: '/humans/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIdEditRoute = LayoutGroupsIdEditRouteImport.update({
  id: '/groups/$id/edit',
  path: '/groups/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderIdEditRoute = LayoutFormBuilderIdEditRouteImport.update({
  id: '/form-builder/$id/edit',
  path: '/form-builder/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouponsIdEditRoute = LayoutCouponsIdEditRouteImport.update({
  id: '/coupons/$id/edit',
  path: '/coupons/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIdEditRoute = LayoutAdminIdEditRouteImport.update({
  id: '/admin/$id/edit',
  path: '/admin/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/attendees': typeof LayoutAttendeesRoute
  '/payments': typeof LayoutPaymentsRoute
  '/settings': typeof LayoutSettingsRoute
  '/admin/new': typeof LayoutAdminNewRoute
  '/applications/new': typeof LayoutApplicationsNewRoute
  '/coupons/new': typeof LayoutCouponsNewRoute
  '/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/groups/new': typeof LayoutGroupsNewRoute
  '/humans/new': typeof LayoutHumansNewRoute
  '/popups/new': typeof LayoutPopupsNewRoute
  '/products/new': typeof LayoutProductsNewRoute
  '/tenants/new': typeof LayoutTenantsNewRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/applications/': typeof LayoutApplicationsIndexRoute
  '/coupons/': typeof LayoutCouponsIndexRoute
  '/form-builder/': typeof LayoutFormBuilderIndexRoute
  '/groups/': typeof LayoutGroupsIndexRoute
  '/humans/': typeof LayoutHumansIndexRoute
  '/popups/': typeof LayoutPopupsIndexRoute
  '/products/': typeof LayoutProductsIndexRoute
  '/tenants/': typeof LayoutTenantsIndexRoute
  '/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/humans/$id/edit': typeof LayoutHumansIdEditRoute
  '/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/tenants/$id/edit': typeof LayoutTenantsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendees': typeof LayoutAttendeesRoute
  '/payments': typeof LayoutPaymentsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/new': typeof LayoutAdminNewRoute
  '/applications/new': typeof LayoutApplicationsNewRoute
  '/coupons/new': typeof LayoutCouponsNewRoute
  '/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/groups/new': typeof LayoutGroupsNewRoute
  '/humans/new': typeof LayoutHumansNewRoute
  '/popups/new': typeof LayoutPopupsNewRoute
  '/products/new': typeof LayoutProductsNewRoute
  '/tenants/new': typeof LayoutTenantsNewRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/applications': typeof LayoutApplicationsIndexRoute
  '/coupons': typeof LayoutCouponsIndexRoute
  '/form-builder': typeof LayoutFormBuilderIndexRoute
  '/groups': typeof LayoutGroupsIndexRoute
  '/humans': typeof LayoutHumansIndexRoute
  '/popups': typeof LayoutPopupsIndexRoute
  '/products': typeof LayoutProductsIndexRoute
  '/tenants': typeof LayoutTenantsIndexRoute
  '/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/humans/$id/edit': typeof LayoutHumansIdEditRoute
  '/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/tenants/$id/edit': typeof LayoutTenantsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/attendees': typeof LayoutAttendeesRoute
  '/_layout/payments': typeof LayoutPaymentsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/new': typeof LayoutAdminNewRoute
  '/_layout/applications/new': typeof LayoutApplicationsNewRoute
  '/_layout/coupons/new': typeof LayoutCouponsNewRoute
  '/_layout/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/_layout/groups/new': typeof LayoutGroupsNewRoute
  '/_layout/humans/new': typeof LayoutHumansNewRoute
  '/_layout/popups/new': typeof LayoutPopupsNewRoute
  '/_layout/products/new': typeof LayoutProductsNewRoute
  '/_layout/tenants/new': typeof LayoutTenantsNewRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/applications/': typeof LayoutApplicationsIndexRoute
  '/_layout/coupons/': typeof LayoutCouponsIndexRoute
  '/_layout/form-builder/': typeof LayoutFormBuilderIndexRoute
  '/_layout/groups/': typeof LayoutGroupsIndexRoute
  '/_layout/humans/': typeof LayoutHumansIndexRoute
  '/_layout/popups/': typeof LayoutPopupsIndexRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
  '/_layout/tenants/': typeof LayoutTenantsIndexRoute
  '/_layout/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/_layout/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/_layout/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/_layout/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/_layout/humans/$id/edit': typeof LayoutHumansIdEditRoute
  '/_layout/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/_layout/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/_layout/tenants/$id/edit': typeof LayoutTenantsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendees'
    | '/payments'
    | '/settings'
    | '/admin/new'
    | '/applications/new'
    | '/coupons/new'
    | '/form-builder/new'
    | '/groups/new'
    | '/humans/new'
    | '/popups/new'
    | '/products/new'
    | '/tenants/new'
    | '/admin/'
    | '/applications/'
    | '/coupons/'
    | '/form-builder/'
    | '/groups/'
    | '/humans/'
    | '/popups/'
    | '/products/'
    | '/tenants/'
    | '/admin/$id/edit'
    | '/coupons/$id/edit'
    | '/form-builder/$id/edit'
    | '/groups/$id/edit'
    | '/humans/$id/edit'
    | '/popups/$id/edit'
    | '/products/$id/edit'
    | '/tenants/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendees'
    | '/payments'
    | '/settings'
    | '/'
    | '/admin/new'
    | '/applications/new'
    | '/coupons/new'
    | '/form-builder/new'
    | '/groups/new'
    | '/humans/new'
    | '/popups/new'
    | '/products/new'
    | '/tenants/new'
    | '/admin'
    | '/applications'
    | '/coupons'
    | '/form-builder'
    | '/groups'
    | '/humans'
    | '/popups'
    | '/products'
    | '/tenants'
    | '/admin/$id/edit'
    | '/coupons/$id/edit'
    | '/form-builder/$id/edit'
    | '/groups/$id/edit'
    | '/humans/$id/edit'
    | '/popups/$id/edit'
    | '/products/$id/edit'
    | '/tenants/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/attendees'
    | '/_layout/payments'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/new'
    | '/_layout/applications/new'
    | '/_layout/coupons/new'
    | '/_layout/form-builder/new'
    | '/_layout/groups/new'
    | '/_layout/humans/new'
    | '/_layout/popups/new'
    | '/_layout/products/new'
    | '/_layout/tenants/new'
    | '/_layout/admin/'
    | '/_layout/applications/'
    | '/_layout/coupons/'
    | '/_layout/form-builder/'
    | '/_layout/groups/'
    | '/_layout/humans/'
    | '/_layout/popups/'
    | '/_layout/products/'
    | '/_layout/tenants/'
    | '/_layout/admin/$id/edit'
    | '/_layout/coupons/$id/edit'
    | '/_layout/form-builder/$id/edit'
    | '/_layout/groups/$id/edit'
    | '/_layout/humans/$id/edit'
    | '/_layout/popups/$id/edit'
    | '/_layout/products/$id/edit'
    | '/_layout/tenants/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendees': {
      id: '/_layout/attendees'
      path: '/attendees'
      fullPath: '/attendees'
      preLoaderRoute: typeof LayoutAttendeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tenants/': {
      id: '/_layout/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof LayoutTenantsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/': {
      id: '/_layout/popups/'
      path: '/popups'
      fullPath: '/popups/'
      preLoaderRoute: typeof LayoutPopupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/': {
      id: '/_layout/humans/'
      path: '/humans'
      fullPath: '/humans/'
      preLoaderRoute: typeof LayoutHumansIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/': {
      id: '/_layout/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof LayoutGroupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/': {
      id: '/_layout/form-builder/'
      path: '/form-builder'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof LayoutFormBuilderIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/': {
      id: '/_layout/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof LayoutCouponsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/': {
      id: '/_layout/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof LayoutApplicationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tenants/new': {
      id: '/_layout/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof LayoutTenantsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/new': {
      id: '/_layout/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof LayoutProductsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/new': {
      id: '/_layout/popups/new'
      path: '/popups/new'
      fullPath: '/popups/new'
      preLoaderRoute: typeof LayoutPopupsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/new': {
      id: '/_layout/humans/new'
      path: '/humans/new'
      fullPath: '/humans/new'
      preLoaderRoute: typeof LayoutHumansNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/new': {
      id: '/_layout/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof LayoutGroupsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/new': {
      id: '/_layout/form-builder/new'
      path: '/form-builder/new'
      fullPath: '/form-builder/new'
      preLoaderRoute: typeof LayoutFormBuilderNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/new': {
      id: '/_layout/coupons/new'
      path: '/coupons/new'
      fullPath: '/coupons/new'
      preLoaderRoute: typeof LayoutCouponsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/new': {
      id: '/_layout/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof LayoutApplicationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/new': {
      id: '/_layout/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof LayoutAdminNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tenants/$id/edit': {
      id: '/_layout/tenants/$id/edit'
      path: '/tenants/$id/edit'
      fullPath: '/tenants/$id/edit'
      preLoaderRoute: typeof LayoutTenantsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/$id/edit': {
      id: '/_layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof LayoutProductsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/$id/edit': {
      id: '/_layout/popups/$id/edit'
      path: '/popups/$id/edit'
      fullPath: '/popups/$id/edit'
      preLoaderRoute: typeof LayoutPopupsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/$id/edit': {
      id: '/_layout/humans/$id/edit'
      path: '/humans/$id/edit'
      fullPath: '/humans/$id/edit'
      preLoaderRoute: typeof LayoutHumansIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/$id/edit': {
      id: '/_layout/groups/$id/edit'
      path: '/groups/$id/edit'
      fullPath: '/groups/$id/edit'
      preLoaderRoute: typeof LayoutGroupsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/$id/edit': {
      id: '/_layout/form-builder/$id/edit'
      path: '/form-builder/$id/edit'
      fullPath: '/form-builder/$id/edit'
      preLoaderRoute: typeof LayoutFormBuilderIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/$id/edit': {
      id: '/_layout/coupons/$id/edit'
      path: '/coupons/$id/edit'
      fullPath: '/coupons/$id/edit'
      preLoaderRoute: typeof LayoutCouponsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/$id/edit': {
      id: '/_layout/admin/$id/edit'
      path: '/admin/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof LayoutAdminIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAttendeesRoute: typeof LayoutAttendeesRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminNewRoute: typeof LayoutAdminNewRoute
  LayoutApplicationsNewRoute: typeof LayoutApplicationsNewRoute
  LayoutCouponsNewRoute: typeof LayoutCouponsNewRoute
  LayoutFormBuilderNewRoute: typeof LayoutFormBuilderNewRoute
  LayoutGroupsNewRoute: typeof LayoutGroupsNewRoute
  LayoutHumansNewRoute: typeof LayoutHumansNewRoute
  LayoutPopupsNewRoute: typeof LayoutPopupsNewRoute
  LayoutProductsNewRoute: typeof LayoutProductsNewRoute
  LayoutTenantsNewRoute: typeof LayoutTenantsNewRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutApplicationsIndexRoute: typeof LayoutApplicationsIndexRoute
  LayoutCouponsIndexRoute: typeof LayoutCouponsIndexRoute
  LayoutFormBuilderIndexRoute: typeof LayoutFormBuilderIndexRoute
  LayoutGroupsIndexRoute: typeof LayoutGroupsIndexRoute
  LayoutHumansIndexRoute: typeof LayoutHumansIndexRoute
  LayoutPopupsIndexRoute: typeof LayoutPopupsIndexRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
  LayoutTenantsIndexRoute: typeof LayoutTenantsIndexRoute
  LayoutAdminIdEditRoute: typeof LayoutAdminIdEditRoute
  LayoutCouponsIdEditRoute: typeof LayoutCouponsIdEditRoute
  LayoutFormBuilderIdEditRoute: typeof LayoutFormBuilderIdEditRoute
  LayoutGroupsIdEditRoute: typeof LayoutGroupsIdEditRoute
  LayoutHumansIdEditRoute: typeof LayoutHumansIdEditRoute
  LayoutPopupsIdEditRoute: typeof LayoutPopupsIdEditRoute
  LayoutProductsIdEditRoute: typeof LayoutProductsIdEditRoute
  LayoutTenantsIdEditRoute: typeof LayoutTenantsIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAttendeesRoute: LayoutAttendeesRoute,
  LayoutPaymentsRoute: LayoutPaymentsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminNewRoute: LayoutAdminNewRoute,
  LayoutApplicationsNewRoute: LayoutApplicationsNewRoute,
  LayoutCouponsNewRoute: LayoutCouponsNewRoute,
  LayoutFormBuilderNewRoute: LayoutFormBuilderNewRoute,
  LayoutGroupsNewRoute: LayoutGroupsNewRoute,
  LayoutHumansNewRoute: LayoutHumansNewRoute,
  LayoutPopupsNewRoute: LayoutPopupsNewRoute,
  LayoutProductsNewRoute: LayoutProductsNewRoute,
  LayoutTenantsNewRoute: LayoutTenantsNewRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutApplicationsIndexRoute: LayoutApplicationsIndexRoute,
  LayoutCouponsIndexRoute: LayoutCouponsIndexRoute,
  LayoutFormBuilderIndexRoute: LayoutFormBuilderIndexRoute,
  LayoutGroupsIndexRoute: LayoutGroupsIndexRoute,
  LayoutHumansIndexRoute: LayoutHumansIndexRoute,
  LayoutPopupsIndexRoute: LayoutPopupsIndexRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
  LayoutTenantsIndexRoute: LayoutTenantsIndexRoute,
  LayoutAdminIdEditRoute: LayoutAdminIdEditRoute,
  LayoutCouponsIdEditRoute: LayoutCouponsIdEditRoute,
  LayoutFormBuilderIdEditRoute: LayoutFormBuilderIdEditRoute,
  LayoutGroupsIdEditRoute: LayoutGroupsIdEditRoute,
  LayoutHumansIdEditRoute: LayoutHumansIdEditRoute,
  LayoutPopupsIdEditRoute: LayoutPopupsIdEditRoute,
  LayoutProductsIdEditRoute: LayoutProductsIdEditRoute,
  LayoutTenantsIdEditRoute: LayoutTenantsIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
