/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutThirdPartyAppsRouteImport } from './routes/_layout/third-party-apps'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout/payments'
import { Route as LayoutOnboardingRouteImport } from './routes/_layout/onboarding'
import { Route as LayoutEmailLogsRouteImport } from './routes/_layout/email-logs'
import { Route as LayoutCheckInRouteImport } from './routes/_layout/check-in'
import { Route as LayoutApiKeysRouteImport } from './routes/_layout/api-keys'
import { Route as LayoutActivityRouteImport } from './routes/_layout/activity'
import { Route as LayoutAbandonedCartsRouteImport } from './routes/_layout/abandoned-carts'
import { Route as LayoutTicketingStepsIndexRouteImport } from './routes/_layout/ticketing-steps/index'
import { Route as LayoutThemeIndexRouteImport } from './routes/_layout/theme/index'
import { Route as LayoutTasksIndexRouteImport } from './routes/_layout/tasks/index'
import { Route as LayoutSalesFlowsIndexRouteImport } from './routes/_layout/sales-flows/index'
import { Route as LayoutReferralsIndexRouteImport } from './routes/_layout/referrals/index'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout/products/index'
import { Route as LayoutPopupsIndexRouteImport } from './routes/_layout/popups/index'
import { Route as LayoutOrganizationsIndexRouteImport } from './routes/_layout/organizations/index'
import { Route as LayoutInvitesIndexRouteImport } from './routes/_layout/invites/index'
import { Route as LayoutHumansIndexRouteImport } from './routes/_layout/humans/index'
import { Route as LayoutGroupsIndexRouteImport } from './routes/_layout/groups/index'
import { Route as LayoutFormBuilderIndexRouteImport } from './routes/_layout/form-builder/index'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutEmailTemplatesIndexRouteImport } from './routes/_layout/email-templates/index'
import { Route as LayoutCouponsIndexRouteImport } from './routes/_layout/coupons/index'
import { Route as LayoutAttendeesIndexRouteImport } from './routes/_layout/attendees/index'
import { Route as LayoutApplicationsIndexRouteImport } from './routes/_layout/applications/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutAccommodationsIndexRouteImport } from './routes/_layout/accommodations/index'
import { Route as LayoutTicketingStepsStepIdRouteImport } from './routes/_layout/ticketing-steps/$stepId'
import { Route as LayoutSalesFlowsNewRouteImport } from './routes/_layout/sales-flows/new'
import { Route as LayoutProductsNewRouteImport } from './routes/_layout/products/new'
import { Route as LayoutPopupsNewRouteImport } from './routes/_layout/popups/new'
import { Route as LayoutOrganizationsNewRouteImport } from './routes/_layout/organizations/new'
import { Route as LayoutInvitesNewRouteImport } from './routes/_layout/invites/new'
import { Route as LayoutHumansIdRouteImport } from './routes/_layout/humans/$id'
import { Route as LayoutGroupsNewRouteImport } from './routes/_layout/groups/new'
import { Route as LayoutFormBuilderNewRouteImport } from './routes/_layout/form-builder/new'
import { Route as LayoutEventsSettingsRouteImport } from './routes/_layout/events/settings'
import { Route as LayoutEventsPropertiesRouteImport } from './routes/_layout/events/properties'
import { Route as LayoutEventsNewRouteImport } from './routes/_layout/events/new'
import { Route as LayoutEventsDayByVenueRouteImport } from './routes/_layout/events/day-by-venue'
import { Route as LayoutEventsEventIdRouteImport } from './routes/_layout/events/$eventId'
import { Route as LayoutCouponsNewRouteImport } from './routes/_layout/coupons/new'
import { Route as LayoutAttendeesAttendeeIdRouteImport } from './routes/_layout/attendees/$attendeeId'
import { Route as LayoutApplicationsReviewQueueRouteImport } from './routes/_layout/applications/review-queue'
import { Route as LayoutApplicationsIdRouteImport } from './routes/_layout/applications/$id'
import { Route as LayoutAdminNewRouteImport } from './routes/_layout/admin/new'
import { Route as LayoutEventsVenuesIndexRouteImport } from './routes/_layout/events/venues/index'
import { Route as LayoutEventsTracksIndexRouteImport } from './routes/_layout/events/tracks/index'
import { Route as LayoutSalesFlowsIdEditRouteImport } from './routes/_layout/sales-flows/$id.edit'
import { Route as LayoutProductsIdEditRouteImport } from './routes/_layout/products/$id.edit'
import { Route as LayoutPopupsIdEditRouteImport } from './routes/_layout/popups/$id.edit'
import { Route as LayoutPopupsIdBulkGrantRouteImport } from './routes/_layout/popups/$id.bulk-grant'
import { Route as LayoutOrganizationsIdEditRouteImport } from './routes/_layout/organizations/$id.edit'
import { Route as LayoutInvitesInviteIdEditRouteImport } from './routes/_layout/invites/$inviteId/edit'
import { Route as LayoutGroupsIdEditRouteImport } from './routes/_layout/groups/$id.edit'
import { Route as LayoutFormBuilderSectionsNewRouteImport } from './routes/_layout/form-builder/sections/new'
import { Route as LayoutFormBuilderIdEditRouteImport } from './routes/_layout/form-builder/$id.edit'
import { Route as LayoutEventsVenuesNewRouteImport } from './routes/_layout/events/venues/new'
import { Route as LayoutEventsTracksNewRouteImport } from './routes/_layout/events/tracks/new'
import { Route as LayoutEventsEventIdEditRouteImport } from './routes/_layout/events/$eventId_.edit'
import { Route as LayoutEmailTemplatesTypeEditRouteImport } from './routes/_layout/email-templates/$type.edit'
import { Route as LayoutCouponsIdEditRouteImport } from './routes/_layout/coupons/$id.edit'
import { Route as LayoutAdminIdEditRouteImport } from './routes/_layout/admin/$id.edit'
import { Route as LayoutAccommodationsRoomsNewRouteImport } from './routes/_layout/accommodations/rooms/new'
import { Route as LayoutFormBuilderSectionsIdEditRouteImport } from './routes/_layout/form-builder/sections/$id.edit'
import { Route as LayoutEventsVenuesVenueIdScheduleRouteImport } from './routes/_layout/events/venues/$venueId.schedule'
import { Route as LayoutEventsVenuesVenueIdEditRouteImport } from './routes/_layout/events/venues/$venueId.edit'
import { Route as LayoutEventsTracksTrackIdEditRouteImport } from './routes/_layout/events/tracks/$trackId.edit'
import { Route as LayoutAccommodationsRoomsIdEditRouteImport } from './routes/_layout/accommodations/rooms/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutThirdPartyAppsRoute = LayoutThirdPartyAppsRouteImport.update({
  id: '/third-party-apps',
  path: '/third-party-apps',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOnboardingRoute = LayoutOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailLogsRoute = LayoutEmailLogsRouteImport.update({
  id: '/email-logs',
  path: '/email-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckInRoute = LayoutCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiKeysRoute = LayoutApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivityRoute = LayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAbandonedCartsRoute = LayoutAbandonedCartsRouteImport.update({
  id: '/abandoned-carts',
  path: '/abandoned-carts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketingStepsIndexRoute =
  LayoutTicketingStepsIndexRouteImport.update({
    id: '/ticketing-steps/',
    path: '/ticketing-steps/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutThemeIndexRoute = LayoutThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksIndexRoute = LayoutTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesFlowsIndexRoute = LayoutSalesFlowsIndexRouteImport.update({
  id: '/sales-flows/',
  path: '/sales-flows/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReferralsIndexRoute = LayoutReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIndexRoute = LayoutPopupsIndexRouteImport.update({
  id: '/popups/',
  path: '/popups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsIndexRoute =
  LayoutOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInvitesIndexRoute = LayoutInvitesIndexRouteImport.update({
  id: '/invites/',
  path: '/invites/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHumansIndexRoute = LayoutHumansIndexRouteImport.update({
  id: '/humans/',
  path: '/humans/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIndexRoute = LayoutGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderIndexRoute = LayoutFormBuilderIndexRouteImport.update({
  id: '/form-builder/',
  path: '/form-builder/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailTemplatesIndexRoute =
  LayoutEmailTemplatesIndexRouteImport.update({
    id: '/email-templates/',
    path: '/email-templates/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCouponsIndexRoute = LayoutCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendeesIndexRoute = LayoutAttendeesIndexRouteImport.update({
  id: '/attendees/',
  path: '/attendees/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsIndexRoute = LayoutApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccommodationsIndexRoute =
  LayoutAccommodationsIndexRouteImport.update({
    id: '/accommodations/',
    path: '/accommodations/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTicketingStepsStepIdRoute =
  LayoutTicketingStepsStepIdRouteImport.update({
    id: '/ticketing-steps/$stepId',
    path: '/ticketing-steps/$stepId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSalesFlowsNewRoute = LayoutSalesFlowsNewRouteImport.update({
  id: '/sales-flows/new',
  path: '/sales-flows/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsNewRoute = LayoutProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsNewRoute = LayoutPopupsNewRouteImport.update({
  id: '/popups/new',
  path: '/popups/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsNewRoute = LayoutOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvitesNewRoute = LayoutInvitesNewRouteImport.update({
  id: '/invites/new',
  path: '/invites/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHumansIdRoute = LayoutHumansIdRouteImport.update({
  id: '/humans/$id',
  path: '/humans/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsNewRoute = LayoutGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderNewRoute = LayoutFormBuilderNewRouteImport.update({
  id: '/form-builder/new',
  path: '/form-builder/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsSettingsRoute = LayoutEventsSettingsRouteImport.update({
  id: '/events/settings',
  path: '/events/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsPropertiesRoute = LayoutEventsPropertiesRouteImport.update({
  id: '/events/properties',
  path: '/events/properties',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsNewRoute = LayoutEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsDayByVenueRoute = LayoutEventsDayByVenueRouteImport.update({
  id: '/events/day-by-venue',
  path: '/events/day-by-venue',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsEventIdRoute = LayoutEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouponsNewRoute = LayoutCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendeesAttendeeIdRoute =
  LayoutAttendeesAttendeeIdRouteImport.update({
    id: '/attendees/$attendeeId',
    path: '/attendees/$attendeeId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApplicationsReviewQueueRoute =
  LayoutApplicationsReviewQueueRouteImport.update({
    id: '/applications/review-queue',
    path: '/applications/review-queue',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApplicationsIdRoute = LayoutApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminNewRoute = LayoutAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsVenuesIndexRoute = LayoutEventsVenuesIndexRouteImport.update({
  id: '/events/venues/',
  path: '/events/venues/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsTracksIndexRoute = LayoutEventsTracksIndexRouteImport.update({
  id: '/events/tracks/',
  path: '/events/tracks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesFlowsIdEditRoute = LayoutSalesFlowsIdEditRouteImport.update({
  id: '/sales-flows/$id/edit',
  path: '/sales-flows/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsIdEditRoute = LayoutProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIdEditRoute = LayoutPopupsIdEditRouteImport.update({
  id: '/popups/$id/edit',
  path: '/popups/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIdBulkGrantRoute = LayoutPopupsIdBulkGrantRouteImport.update({
  id: '/popups/$id/bulk-grant',
  path: '/popups/$id/bulk-grant',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsIdEditRoute =
  LayoutOrganizationsIdEditRouteImport.update({
    id: '/organizations/$id/edit',
    path: '/organizations/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutInvitesInviteIdEditRoute =
  LayoutInvitesInviteIdEditRouteImport.update({
    id: '/invites/$inviteId/edit',
    path: '/invites/$inviteId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutGroupsIdEditRoute = LayoutGroupsIdEditRouteImport.update({
  id: '/groups/$id/edit',
  path: '/groups/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderSectionsNewRoute =
  LayoutFormBuilderSectionsNewRouteImport.update({
    id: '/form-builder/sections/new',
    path: '/form-builder/sections/new',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFormBuilderIdEditRoute = LayoutFormBuilderIdEditRouteImport.update({
  id: '/form-builder/$id/edit',
  path: '/form-builder/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsVenuesNewRoute = LayoutEventsVenuesNewRouteImport.update({
  id: '/events/venues/new',
  path: '/events/venues/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsTracksNewRoute = LayoutEventsTracksNewRouteImport.update({
  id: '/events/tracks/new',
  path: '/events/tracks/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsEventIdEditRoute = LayoutEventsEventIdEditRouteImport.update({
  id: '/events/$eventId_/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailTemplatesTypeEditRoute =
  LayoutEmailTemplatesTypeEditRouteImport.update({
    id: '/email-templates/$type/edit',
    path: '/email-templates/$type/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCouponsIdEditRoute = LayoutCouponsIdEditRouteImport.update({
  id: '/coupons/$id/edit',
  path: '/coupons/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIdEditRoute = LayoutAdminIdEditRouteImport.update({
  id: '/admin/$id/edit',
  path: '/admin/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccommodationsRoomsNewRoute =
  LayoutAccommodationsRoomsNewRouteImport.update({
    id: '/accommodations/rooms/new',
    path: '/accommodations/rooms/new',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFormBuilderSectionsIdEditRoute =
  LayoutFormBuilderSectionsIdEditRouteImport.update({
    id: '/form-builder/sections/$id/edit',
    path: '/form-builder/sections/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEventsVenuesVenueIdScheduleRoute =
  LayoutEventsVenuesVenueIdScheduleRouteImport.update({
    id: '/events/venues/$venueId/schedule',
    path: '/events/venues/$venueId/schedule',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEventsVenuesVenueIdEditRoute =
  LayoutEventsVenuesVenueIdEditRouteImport.update({
    id: '/events/venues/$venueId/edit',
    path: '/events/venues/$venueId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEventsTracksTrackIdEditRoute =
  LayoutEventsTracksTrackIdEditRouteImport.update({
    id: '/events/tracks/$trackId/edit',
    path: '/events/tracks/$trackId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAccommodationsRoomsIdEditRoute =
  LayoutAccommodationsRoomsIdEditRouteImport.update({
    id: '/accommodations/rooms/$id/edit',
    path: '/accommodations/rooms/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/abandoned-carts': typeof LayoutAbandonedCartsRoute
  '/activity': typeof LayoutActivityRoute
  '/api-keys': typeof LayoutApiKeysRoute
  '/check-in': typeof LayoutCheckInRoute
  '/email-logs': typeof LayoutEmailLogsRoute
  '/onboarding': typeof LayoutOnboardingRoute
  '/payments': typeof LayoutPaymentsRoute
  '/settings': typeof LayoutSettingsRoute
  '/third-party-apps': typeof LayoutThirdPartyAppsRoute
  '/admin/new': typeof LayoutAdminNewRoute
  '/applications/$id': typeof LayoutApplicationsIdRoute
  '/applications/review-queue': typeof LayoutApplicationsReviewQueueRoute
  '/attendees/$attendeeId': typeof LayoutAttendeesAttendeeIdRoute
  '/coupons/new': typeof LayoutCouponsNewRoute
  '/events/$eventId': typeof LayoutEventsEventIdRoute
  '/events/day-by-venue': typeof LayoutEventsDayByVenueRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/events/properties': typeof LayoutEventsPropertiesRoute
  '/events/settings': typeof LayoutEventsSettingsRoute
  '/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/groups/new': typeof LayoutGroupsNewRoute
  '/humans/$id': typeof LayoutHumansIdRoute
  '/invites/new': typeof LayoutInvitesNewRoute
  '/organizations/new': typeof LayoutOrganizationsNewRoute
  '/popups/new': typeof LayoutPopupsNewRoute
  '/products/new': typeof LayoutProductsNewRoute
  '/sales-flows/new': typeof LayoutSalesFlowsNewRoute
  '/ticketing-steps/$stepId': typeof LayoutTicketingStepsStepIdRoute
  '/accommodations/': typeof LayoutAccommodationsIndexRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/applications/': typeof LayoutApplicationsIndexRoute
  '/attendees/': typeof LayoutAttendeesIndexRoute
  '/coupons/': typeof LayoutCouponsIndexRoute
  '/email-templates/': typeof LayoutEmailTemplatesIndexRoute
  '/events/': typeof LayoutEventsIndexRoute
  '/form-builder/': typeof LayoutFormBuilderIndexRoute
  '/groups/': typeof LayoutGroupsIndexRoute
  '/humans/': typeof LayoutHumansIndexRoute
  '/invites/': typeof LayoutInvitesIndexRoute
  '/organizations/': typeof LayoutOrganizationsIndexRoute
  '/popups/': typeof LayoutPopupsIndexRoute
  '/products/': typeof LayoutProductsIndexRoute
  '/referrals/': typeof LayoutReferralsIndexRoute
  '/sales-flows/': typeof LayoutSalesFlowsIndexRoute
  '/tasks/': typeof LayoutTasksIndexRoute
  '/theme/': typeof LayoutThemeIndexRoute
  '/ticketing-steps/': typeof LayoutTicketingStepsIndexRoute
  '/accommodations/rooms/new': typeof LayoutAccommodationsRoomsNewRoute
  '/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/email-templates/$type/edit': typeof LayoutEmailTemplatesTypeEditRoute
  '/events/$eventId/edit': typeof LayoutEventsEventIdEditRoute
  '/events/tracks/new': typeof LayoutEventsTracksNewRoute
  '/events/venues/new': typeof LayoutEventsVenuesNewRoute
  '/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/form-builder/sections/new': typeof LayoutFormBuilderSectionsNewRoute
  '/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/invites/$inviteId/edit': typeof LayoutInvitesInviteIdEditRoute
  '/organizations/$id/edit': typeof LayoutOrganizationsIdEditRoute
  '/popups/$id/bulk-grant': typeof LayoutPopupsIdBulkGrantRoute
  '/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/sales-flows/$id/edit': typeof LayoutSalesFlowsIdEditRoute
  '/events/tracks/': typeof LayoutEventsTracksIndexRoute
  '/events/venues/': typeof LayoutEventsVenuesIndexRoute
  '/accommodations/rooms/$id/edit': typeof LayoutAccommodationsRoomsIdEditRoute
  '/events/tracks/$trackId/edit': typeof LayoutEventsTracksTrackIdEditRoute
  '/events/venues/$venueId/edit': typeof LayoutEventsVenuesVenueIdEditRoute
  '/events/venues/$venueId/schedule': typeof LayoutEventsVenuesVenueIdScheduleRoute
  '/form-builder/sections/$id/edit': typeof LayoutFormBuilderSectionsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/abandoned-carts': typeof LayoutAbandonedCartsRoute
  '/activity': typeof LayoutActivityRoute
  '/api-keys': typeof LayoutApiKeysRoute
  '/check-in': typeof LayoutCheckInRoute
  '/email-logs': typeof LayoutEmailLogsRoute
  '/onboarding': typeof LayoutOnboardingRoute
  '/payments': typeof LayoutPaymentsRoute
  '/settings': typeof LayoutSettingsRoute
  '/third-party-apps': typeof LayoutThirdPartyAppsRoute
  '/': typeof LayoutIndexRoute
  '/admin/new': typeof LayoutAdminNewRoute
  '/applications/$id': typeof LayoutApplicationsIdRoute
  '/applications/review-queue': typeof LayoutApplicationsReviewQueueRoute
  '/attendees/$attendeeId': typeof LayoutAttendeesAttendeeIdRoute
  '/coupons/new': typeof LayoutCouponsNewRoute
  '/events/$eventId': typeof LayoutEventsEventIdRoute
  '/events/day-by-venue': typeof LayoutEventsDayByVenueRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/events/properties': typeof LayoutEventsPropertiesRoute
  '/events/settings': typeof LayoutEventsSettingsRoute
  '/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/groups/new': typeof LayoutGroupsNewRoute
  '/humans/$id': typeof LayoutHumansIdRoute
  '/invites/new': typeof LayoutInvitesNewRoute
  '/organizations/new': typeof LayoutOrganizationsNewRoute
  '/popups/new': typeof LayoutPopupsNewRoute
  '/products/new': typeof LayoutProductsNewRoute
  '/sales-flows/new': typeof LayoutSalesFlowsNewRoute
  '/ticketing-steps/$stepId': typeof LayoutTicketingStepsStepIdRoute
  '/accommodations': typeof LayoutAccommodationsIndexRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/applications': typeof LayoutApplicationsIndexRoute
  '/attendees': typeof LayoutAttendeesIndexRoute
  '/coupons': typeof LayoutCouponsIndexRoute
  '/email-templates': typeof LayoutEmailTemplatesIndexRoute
  '/events': typeof LayoutEventsIndexRoute
  '/form-builder': typeof LayoutFormBuilderIndexRoute
  '/groups': typeof LayoutGroupsIndexRoute
  '/humans': typeof LayoutHumansIndexRoute
  '/invites': typeof LayoutInvitesIndexRoute
  '/organizations': typeof LayoutOrganizationsIndexRoute
  '/popups': typeof LayoutPopupsIndexRoute
  '/products': typeof LayoutProductsIndexRoute
  '/referrals': typeof LayoutReferralsIndexRoute
  '/sales-flows': typeof LayoutSalesFlowsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/theme': typeof LayoutThemeIndexRoute
  '/ticketing-steps': typeof LayoutTicketingStepsIndexRoute
  '/accommodations/rooms/new': typeof LayoutAccommodationsRoomsNewRoute
  '/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/email-templates/$type/edit': typeof LayoutEmailTemplatesTypeEditRoute
  '/events/$eventId/edit': typeof LayoutEventsEventIdEditRoute
  '/events/tracks/new': typeof LayoutEventsTracksNewRoute
  '/events/venues/new': typeof LayoutEventsVenuesNewRoute
  '/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/form-builder/sections/new': typeof LayoutFormBuilderSectionsNewRoute
  '/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/invites/$inviteId/edit': typeof LayoutInvitesInviteIdEditRoute
  '/organizations/$id/edit': typeof LayoutOrganizationsIdEditRoute
  '/popups/$id/bulk-grant': typeof LayoutPopupsIdBulkGrantRoute
  '/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/sales-flows/$id/edit': typeof LayoutSalesFlowsIdEditRoute
  '/events/tracks': typeof LayoutEventsTracksIndexRoute
  '/events/venues': typeof LayoutEventsVenuesIndexRoute
  '/accommodations/rooms/$id/edit': typeof LayoutAccommodationsRoomsIdEditRoute
  '/events/tracks/$trackId/edit': typeof LayoutEventsTracksTrackIdEditRoute
  '/events/venues/$venueId/edit': typeof LayoutEventsVenuesVenueIdEditRoute
  '/events/venues/$venueId/schedule': typeof LayoutEventsVenuesVenueIdScheduleRoute
  '/form-builder/sections/$id/edit': typeof LayoutFormBuilderSectionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/abandoned-carts': typeof LayoutAbandonedCartsRoute
  '/_layout/activity': typeof LayoutActivityRoute
  '/_layout/api-keys': typeof LayoutApiKeysRoute
  '/_layout/check-in': typeof LayoutCheckInRoute
  '/_layout/email-logs': typeof LayoutEmailLogsRoute
  '/_layout/onboarding': typeof LayoutOnboardingRoute
  '/_layout/payments': typeof LayoutPaymentsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/third-party-apps': typeof LayoutThirdPartyAppsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/new': typeof LayoutAdminNewRoute
  '/_layout/applications/$id': typeof LayoutApplicationsIdRoute
  '/_layout/applications/review-queue': typeof LayoutApplicationsReviewQueueRoute
  '/_layout/attendees/$attendeeId': typeof LayoutAttendeesAttendeeIdRoute
  '/_layout/coupons/new': typeof LayoutCouponsNewRoute
  '/_layout/events/$eventId': typeof LayoutEventsEventIdRoute
  '/_layout/events/day-by-venue': typeof LayoutEventsDayByVenueRoute
  '/_layout/events/new': typeof LayoutEventsNewRoute
  '/_layout/events/properties': typeof LayoutEventsPropertiesRoute
  '/_layout/events/settings': typeof LayoutEventsSettingsRoute
  '/_layout/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/_layout/groups/new': typeof LayoutGroupsNewRoute
  '/_layout/humans/$id': typeof LayoutHumansIdRoute
  '/_layout/invites/new': typeof LayoutInvitesNewRoute
  '/_layout/organizations/new': typeof LayoutOrganizationsNewRoute
  '/_layout/popups/new': typeof LayoutPopupsNewRoute
  '/_layout/products/new': typeof LayoutProductsNewRoute
  '/_layout/sales-flows/new': typeof LayoutSalesFlowsNewRoute
  '/_layout/ticketing-steps/$stepId': typeof LayoutTicketingStepsStepIdRoute
  '/_layout/accommodations/': typeof LayoutAccommodationsIndexRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/applications/': typeof LayoutApplicationsIndexRoute
  '/_layout/attendees/': typeof LayoutAttendeesIndexRoute
  '/_layout/coupons/': typeof LayoutCouponsIndexRoute
  '/_layout/email-templates/': typeof LayoutEmailTemplatesIndexRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
  '/_layout/form-builder/': typeof LayoutFormBuilderIndexRoute
  '/_layout/groups/': typeof LayoutGroupsIndexRoute
  '/_layout/humans/': typeof LayoutHumansIndexRoute
  '/_layout/invites/': typeof LayoutInvitesIndexRoute
  '/_layout/organizations/': typeof LayoutOrganizationsIndexRoute
  '/_layout/popups/': typeof LayoutPopupsIndexRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
  '/_layout/referrals/': typeof LayoutReferralsIndexRoute
  '/_layout/sales-flows/': typeof LayoutSalesFlowsIndexRoute
  '/_layout/tasks/': typeof LayoutTasksIndexRoute
  '/_layout/theme/': typeof LayoutThemeIndexRoute
  '/_layout/ticketing-steps/': typeof LayoutTicketingStepsIndexRoute
  '/_layout/accommodations/rooms/new': typeof LayoutAccommodationsRoomsNewRoute
  '/_layout/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/_layout/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/_layout/email-templates/$type/edit': typeof LayoutEmailTemplatesTypeEditRoute
  '/_layout/events/$eventId_/edit': typeof LayoutEventsEventIdEditRoute
  '/_layout/events/tracks/new': typeof LayoutEventsTracksNewRoute
  '/_layout/events/venues/new': typeof LayoutEventsVenuesNewRoute
  '/_layout/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/_layout/form-builder/sections/new': typeof LayoutFormBuilderSectionsNewRoute
  '/_layout/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/_layout/invites/$inviteId/edit': typeof LayoutInvitesInviteIdEditRoute
  '/_layout/organizations/$id/edit': typeof LayoutOrganizationsIdEditRoute
  '/_layout/popups/$id/bulk-grant': typeof LayoutPopupsIdBulkGrantRoute
  '/_layout/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/_layout/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/_layout/sales-flows/$id/edit': typeof LayoutSalesFlowsIdEditRoute
  '/_layout/events/tracks/': typeof LayoutEventsTracksIndexRoute
  '/_layout/events/venues/': typeof LayoutEventsVenuesIndexRoute
  '/_layout/accommodations/rooms/$id/edit': typeof LayoutAccommodationsRoomsIdEditRoute
  '/_layout/events/tracks/$trackId/edit': typeof LayoutEventsTracksTrackIdEditRoute
  '/_layout/events/venues/$venueId/edit': typeof LayoutEventsVenuesVenueIdEditRoute
  '/_layout/events/venues/$venueId/schedule': typeof LayoutEventsVenuesVenueIdScheduleRoute
  '/_layout/form-builder/sections/$id/edit': typeof LayoutFormBuilderSectionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/abandoned-carts'
    | '/activity'
    | '/api-keys'
    | '/check-in'
    | '/email-logs'
    | '/onboarding'
    | '/payments'
    | '/settings'
    | '/third-party-apps'
    | '/admin/new'
    | '/applications/$id'
    | '/applications/review-queue'
    | '/attendees/$attendeeId'
    | '/coupons/new'
    | '/events/$eventId'
    | '/events/day-by-venue'
    | '/events/new'
    | '/events/properties'
    | '/events/settings'
    | '/form-builder/new'
    | '/groups/new'
    | '/humans/$id'
    | '/invites/new'
    | '/organizations/new'
    | '/popups/new'
    | '/products/new'
    | '/sales-flows/new'
    | '/ticketing-steps/$stepId'
    | '/accommodations/'
    | '/admin/'
    | '/applications/'
    | '/attendees/'
    | '/coupons/'
    | '/email-templates/'
    | '/events/'
    | '/form-builder/'
    | '/groups/'
    | '/humans/'
    | '/invites/'
    | '/organizations/'
    | '/popups/'
    | '/products/'
    | '/referrals/'
    | '/sales-flows/'
    | '/tasks/'
    | '/theme/'
    | '/ticketing-steps/'
    | '/accommodations/rooms/new'
    | '/admin/$id/edit'
    | '/coupons/$id/edit'
    | '/email-templates/$type/edit'
    | '/events/$eventId/edit'
    | '/events/tracks/new'
    | '/events/venues/new'
    | '/form-builder/$id/edit'
    | '/form-builder/sections/new'
    | '/groups/$id/edit'
    | '/invites/$inviteId/edit'
    | '/organizations/$id/edit'
    | '/popups/$id/bulk-grant'
    | '/popups/$id/edit'
    | '/products/$id/edit'
    | '/sales-flows/$id/edit'
    | '/events/tracks/'
    | '/events/venues/'
    | '/accommodations/rooms/$id/edit'
    | '/events/tracks/$trackId/edit'
    | '/events/venues/$venueId/edit'
    | '/events/venues/$venueId/schedule'
    | '/form-builder/sections/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/abandoned-carts'
    | '/activity'
    | '/api-keys'
    | '/check-in'
    | '/email-logs'
    | '/onboarding'
    | '/payments'
    | '/settings'
    | '/third-party-apps'
    | '/'
    | '/admin/new'
    | '/applications/$id'
    | '/applications/review-queue'
    | '/attendees/$attendeeId'
    | '/coupons/new'
    | '/events/$eventId'
    | '/events/day-by-venue'
    | '/events/new'
    | '/events/properties'
    | '/events/settings'
    | '/form-builder/new'
    | '/groups/new'
    | '/humans/$id'
    | '/invites/new'
    | '/organizations/new'
    | '/popups/new'
    | '/products/new'
    | '/sales-flows/new'
    | '/ticketing-steps/$stepId'
    | '/accommodations'
    | '/admin'
    | '/applications'
    | '/attendees'
    | '/coupons'
    | '/email-templates'
    | '/events'
    | '/form-builder'
    | '/groups'
    | '/humans'
    | '/invites'
    | '/organizations'
    | '/popups'
    | '/products'
    | '/referrals'
    | '/sales-flows'
    | '/tasks'
    | '/theme'
    | '/ticketing-steps'
    | '/accommodations/rooms/new'
    | '/admin/$id/edit'
    | '/coupons/$id/edit'
    | '/email-templates/$type/edit'
    | '/events/$eventId/edit'
    | '/events/tracks/new'
    | '/events/venues/new'
    | '/form-builder/$id/edit'
    | '/form-builder/sections/new'
    | '/groups/$id/edit'
    | '/invites/$inviteId/edit'
    | '/organizations/$id/edit'
    | '/popups/$id/bulk-grant'
    | '/popups/$id/edit'
    | '/products/$id/edit'
    | '/sales-flows/$id/edit'
    | '/events/tracks'
    | '/events/venues'
    | '/accommodations/rooms/$id/edit'
    | '/events/tracks/$trackId/edit'
    | '/events/venues/$venueId/edit'
    | '/events/venues/$venueId/schedule'
    | '/form-builder/sections/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/abandoned-carts'
    | '/_layout/activity'
    | '/_layout/api-keys'
    | '/_layout/check-in'
    | '/_layout/email-logs'
    | '/_layout/onboarding'
    | '/_layout/payments'
    | '/_layout/settings'
    | '/_layout/third-party-apps'
    | '/_layout/'
    | '/_layout/admin/new'
    | '/_layout/applications/$id'
    | '/_layout/applications/review-queue'
    | '/_layout/attendees/$attendeeId'
    | '/_layout/coupons/new'
    | '/_layout/events/$eventId'
    | '/_layout/events/day-by-venue'
    | '/_layout/events/new'
    | '/_layout/events/properties'
    | '/_layout/events/settings'
    | '/_layout/form-builder/new'
    | '/_layout/groups/new'
    | '/_layout/humans/$id'
    | '/_layout/invites/new'
    | '/_layout/organizations/new'
    | '/_layout/popups/new'
    | '/_layout/products/new'
    | '/_layout/sales-flows/new'
    | '/_layout/ticketing-steps/$stepId'
    | '/_layout/accommodations/'
    | '/_layout/admin/'
    | '/_layout/applications/'
    | '/_layout/attendees/'
    | '/_layout/coupons/'
    | '/_layout/email-templates/'
    | '/_layout/events/'
    | '/_layout/form-builder/'
    | '/_layout/groups/'
    | '/_layout/humans/'
    | '/_layout/invites/'
    | '/_layout/organizations/'
    | '/_layout/popups/'
    | '/_layout/products/'
    | '/_layout/referrals/'
    | '/_layout/sales-flows/'
    | '/_layout/tasks/'
    | '/_layout/theme/'
    | '/_layout/ticketing-steps/'
    | '/_layout/accommodations/rooms/new'
    | '/_layout/admin/$id/edit'
    | '/_layout/coupons/$id/edit'
    | '/_layout/email-templates/$type/edit'
    | '/_layout/events/$eventId_/edit'
    | '/_layout/events/tracks/new'
    | '/_layout/events/venues/new'
    | '/_layout/form-builder/$id/edit'
    | '/_layout/form-builder/sections/new'
    | '/_layout/groups/$id/edit'
    | '/_layout/invites/$inviteId/edit'
    | '/_layout/organizations/$id/edit'
    | '/_layout/popups/$id/bulk-grant'
    | '/_layout/popups/$id/edit'
    | '/_layout/products/$id/edit'
    | '/_layout/sales-flows/$id/edit'
    | '/_layout/events/tracks/'
    | '/_layout/events/venues/'
    | '/_layout/accommodations/rooms/$id/edit'
    | '/_layout/events/tracks/$trackId/edit'
    | '/_layout/events/venues/$venueId/edit'
    | '/_layout/events/venues/$venueId/schedule'
    | '/_layout/form-builder/sections/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/third-party-apps': {
      id: '/_layout/third-party-apps'
      path: '/third-party-apps'
      fullPath: '/third-party-apps'
      preLoaderRoute: typeof LayoutThirdPartyAppsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/onboarding': {
      id: '/_layout/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof LayoutOnboardingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-logs': {
      id: '/_layout/email-logs'
      path: '/email-logs'
      fullPath: '/email-logs'
      preLoaderRoute: typeof LayoutEmailLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/check-in': {
      id: '/_layout/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof LayoutCheckInRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-keys': {
      id: '/_layout/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof LayoutApiKeysRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activity': {
      id: '/_layout/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof LayoutActivityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/abandoned-carts': {
      id: '/_layout/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/abandoned-carts'
      preLoaderRoute: typeof LayoutAbandonedCartsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticketing-steps/': {
      id: '/_layout/ticketing-steps/'
      path: '/ticketing-steps'
      fullPath: '/ticketing-steps/'
      preLoaderRoute: typeof LayoutTicketingStepsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/theme/': {
      id: '/_layout/theme/'
      path: '/theme'
      fullPath: '/theme/'
      preLoaderRoute: typeof LayoutThemeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/': {
      id: '/_layout/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof LayoutTasksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales-flows/': {
      id: '/_layout/sales-flows/'
      path: '/sales-flows'
      fullPath: '/sales-flows/'
      preLoaderRoute: typeof LayoutSalesFlowsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/referrals/': {
      id: '/_layout/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof LayoutReferralsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/': {
      id: '/_layout/popups/'
      path: '/popups'
      fullPath: '/popups/'
      preLoaderRoute: typeof LayoutPopupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations/': {
      id: '/_layout/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutOrganizationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invites/': {
      id: '/_layout/invites/'
      path: '/invites'
      fullPath: '/invites/'
      preLoaderRoute: typeof LayoutInvitesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/': {
      id: '/_layout/humans/'
      path: '/humans'
      fullPath: '/humans/'
      preLoaderRoute: typeof LayoutHumansIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/': {
      id: '/_layout/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof LayoutGroupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/': {
      id: '/_layout/form-builder/'
      path: '/form-builder'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof LayoutFormBuilderIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-templates/': {
      id: '/_layout/email-templates/'
      path: '/email-templates'
      fullPath: '/email-templates/'
      preLoaderRoute: typeof LayoutEmailTemplatesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/': {
      id: '/_layout/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof LayoutCouponsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendees/': {
      id: '/_layout/attendees/'
      path: '/attendees'
      fullPath: '/attendees/'
      preLoaderRoute: typeof LayoutAttendeesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/': {
      id: '/_layout/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof LayoutApplicationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accommodations/': {
      id: '/_layout/accommodations/'
      path: '/accommodations'
      fullPath: '/accommodations/'
      preLoaderRoute: typeof LayoutAccommodationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticketing-steps/$stepId': {
      id: '/_layout/ticketing-steps/$stepId'
      path: '/ticketing-steps/$stepId'
      fullPath: '/ticketing-steps/$stepId'
      preLoaderRoute: typeof LayoutTicketingStepsStepIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales-flows/new': {
      id: '/_layout/sales-flows/new'
      path: '/sales-flows/new'
      fullPath: '/sales-flows/new'
      preLoaderRoute: typeof LayoutSalesFlowsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/new': {
      id: '/_layout/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof LayoutProductsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/new': {
      id: '/_layout/popups/new'
      path: '/popups/new'
      fullPath: '/popups/new'
      preLoaderRoute: typeof LayoutPopupsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations/new': {
      id: '/_layout/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutOrganizationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invites/new': {
      id: '/_layout/invites/new'
      path: '/invites/new'
      fullPath: '/invites/new'
      preLoaderRoute: typeof LayoutInvitesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/$id': {
      id: '/_layout/humans/$id'
      path: '/humans/$id'
      fullPath: '/humans/$id'
      preLoaderRoute: typeof LayoutHumansIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/new': {
      id: '/_layout/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof LayoutGroupsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/new': {
      id: '/_layout/form-builder/new'
      path: '/form-builder/new'
      fullPath: '/form-builder/new'
      preLoaderRoute: typeof LayoutFormBuilderNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/settings': {
      id: '/_layout/events/settings'
      path: '/events/settings'
      fullPath: '/events/settings'
      preLoaderRoute: typeof LayoutEventsSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/properties': {
      id: '/_layout/events/properties'
      path: '/events/properties'
      fullPath: '/events/properties'
      preLoaderRoute: typeof LayoutEventsPropertiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/new': {
      id: '/_layout/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof LayoutEventsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/day-by-venue': {
      id: '/_layout/events/day-by-venue'
      path: '/events/day-by-venue'
      fullPath: '/events/day-by-venue'
      preLoaderRoute: typeof LayoutEventsDayByVenueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/$eventId': {
      id: '/_layout/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof LayoutEventsEventIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/new': {
      id: '/_layout/coupons/new'
      path: '/coupons/new'
      fullPath: '/coupons/new'
      preLoaderRoute: typeof LayoutCouponsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendees/$attendeeId': {
      id: '/_layout/attendees/$attendeeId'
      path: '/attendees/$attendeeId'
      fullPath: '/attendees/$attendeeId'
      preLoaderRoute: typeof LayoutAttendeesAttendeeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/review-queue': {
      id: '/_layout/applications/review-queue'
      path: '/applications/review-queue'
      fullPath: '/applications/review-queue'
      preLoaderRoute: typeof LayoutApplicationsReviewQueueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/$id': {
      id: '/_layout/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof LayoutApplicationsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/new': {
      id: '/_layout/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof LayoutAdminNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues/': {
      id: '/_layout/events/venues/'
      path: '/events/venues'
      fullPath: '/events/venues/'
      preLoaderRoute: typeof LayoutEventsVenuesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/tracks/': {
      id: '/_layout/events/tracks/'
      path: '/events/tracks'
      fullPath: '/events/tracks/'
      preLoaderRoute: typeof LayoutEventsTracksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales-flows/$id/edit': {
      id: '/_layout/sales-flows/$id/edit'
      path: '/sales-flows/$id/edit'
      fullPath: '/sales-flows/$id/edit'
      preLoaderRoute: typeof LayoutSalesFlowsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/$id/edit': {
      id: '/_layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof LayoutProductsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/$id/edit': {
      id: '/_layout/popups/$id/edit'
      path: '/popups/$id/edit'
      fullPath: '/popups/$id/edit'
      preLoaderRoute: typeof LayoutPopupsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/$id/bulk-grant': {
      id: '/_layout/popups/$id/bulk-grant'
      path: '/popups/$id/bulk-grant'
      fullPath: '/popups/$id/bulk-grant'
      preLoaderRoute: typeof LayoutPopupsIdBulkGrantRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations/$id/edit': {
      id: '/_layout/organizations/$id/edit'
      path: '/organizations/$id/edit'
      fullPath: '/organizations/$id/edit'
      preLoaderRoute: typeof LayoutOrganizationsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/invites/$inviteId/edit': {
      id: '/_layout/invites/$inviteId/edit'
      path: '/invites/$inviteId/edit'
      fullPath: '/invites/$inviteId/edit'
      preLoaderRoute: typeof LayoutInvitesInviteIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/$id/edit': {
      id: '/_layout/groups/$id/edit'
      path: '/groups/$id/edit'
      fullPath: '/groups/$id/edit'
      preLoaderRoute: typeof LayoutGroupsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/sections/new': {
      id: '/_layout/form-builder/sections/new'
      path: '/form-builder/sections/new'
      fullPath: '/form-builder/sections/new'
      preLoaderRoute: typeof LayoutFormBuilderSectionsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/$id/edit': {
      id: '/_layout/form-builder/$id/edit'
      path: '/form-builder/$id/edit'
      fullPath: '/form-builder/$id/edit'
      preLoaderRoute: typeof LayoutFormBuilderIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues/new': {
      id: '/_layout/events/venues/new'
      path: '/events/venues/new'
      fullPath: '/events/venues/new'
      preLoaderRoute: typeof LayoutEventsVenuesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/tracks/new': {
      id: '/_layout/events/tracks/new'
      path: '/events/tracks/new'
      fullPath: '/events/tracks/new'
      preLoaderRoute: typeof LayoutEventsTracksNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/$eventId_/edit': {
      id: '/_layout/events/$eventId_/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof LayoutEventsEventIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-templates/$type/edit': {
      id: '/_layout/email-templates/$type/edit'
      path: '/email-templates/$type/edit'
      fullPath: '/email-templates/$type/edit'
      preLoaderRoute: typeof LayoutEmailTemplatesTypeEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/$id/edit': {
      id: '/_layout/coupons/$id/edit'
      path: '/coupons/$id/edit'
      fullPath: '/coupons/$id/edit'
      preLoaderRoute: typeof LayoutCouponsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/$id/edit': {
      id: '/_layout/admin/$id/edit'
      path: '/admin/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof LayoutAdminIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accommodations/rooms/new': {
      id: '/_layout/accommodations/rooms/new'
      path: '/accommodations/rooms/new'
      fullPath: '/accommodations/rooms/new'
      preLoaderRoute: typeof LayoutAccommodationsRoomsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/sections/$id/edit': {
      id: '/_layout/form-builder/sections/$id/edit'
      path: '/form-builder/sections/$id/edit'
      fullPath: '/form-builder/sections/$id/edit'
      preLoaderRoute: typeof LayoutFormBuilderSectionsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues/$venueId/schedule': {
      id: '/_layout/events/venues/$venueId/schedule'
      path: '/events/venues/$venueId/schedule'
      fullPath: '/events/venues/$venueId/schedule'
      preLoaderRoute: typeof LayoutEventsVenuesVenueIdScheduleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues/$venueId/edit': {
      id: '/_layout/events/venues/$venueId/edit'
      path: '/events/venues/$venueId/edit'
      fullPath: '/events/venues/$venueId/edit'
      preLoaderRoute: typeof LayoutEventsVenuesVenueIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/tracks/$trackId/edit': {
      id: '/_layout/events/tracks/$trackId/edit'
      path: '/events/tracks/$trackId/edit'
      fullPath: '/events/tracks/$trackId/edit'
      preLoaderRoute: typeof LayoutEventsTracksTrackIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accommodations/rooms/$id/edit': {
      id: '/_layout/accommodations/rooms/$id/edit'
      path: '/accommodations/rooms/$id/edit'
      fullPath: '/accommodations/rooms/$id/edit'
      preLoaderRoute: typeof LayoutAccommodationsRoomsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAbandonedCartsRoute: typeof LayoutAbandonedCartsRoute
  LayoutActivityRoute: typeof LayoutActivityRoute
  LayoutApiKeysRoute: typeof LayoutApiKeysRoute
  LayoutCheckInRoute: typeof LayoutCheckInRoute
  LayoutEmailLogsRoute: typeof LayoutEmailLogsRoute
  LayoutOnboardingRoute: typeof LayoutOnboardingRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutThirdPartyAppsRoute: typeof LayoutThirdPartyAppsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminNewRoute: typeof LayoutAdminNewRoute
  LayoutApplicationsIdRoute: typeof LayoutApplicationsIdRoute
  LayoutApplicationsReviewQueueRoute: typeof LayoutApplicationsReviewQueueRoute
  LayoutAttendeesAttendeeIdRoute: typeof LayoutAttendeesAttendeeIdRoute
  LayoutCouponsNewRoute: typeof LayoutCouponsNewRoute
  LayoutEventsEventIdRoute: typeof LayoutEventsEventIdRoute
  LayoutEventsDayByVenueRoute: typeof LayoutEventsDayByVenueRoute
  LayoutEventsNewRoute: typeof LayoutEventsNewRoute
  LayoutEventsPropertiesRoute: typeof LayoutEventsPropertiesRoute
  LayoutEventsSettingsRoute: typeof LayoutEventsSettingsRoute
  LayoutFormBuilderNewRoute: typeof LayoutFormBuilderNewRoute
  LayoutGroupsNewRoute: typeof LayoutGroupsNewRoute
  LayoutHumansIdRoute: typeof LayoutHumansIdRoute
  LayoutInvitesNewRoute: typeof LayoutInvitesNewRoute
  LayoutOrganizationsNewRoute: typeof LayoutOrganizationsNewRoute
  LayoutPopupsNewRoute: typeof LayoutPopupsNewRoute
  LayoutProductsNewRoute: typeof LayoutProductsNewRoute
  LayoutSalesFlowsNewRoute: typeof LayoutSalesFlowsNewRoute
  LayoutTicketingStepsStepIdRoute: typeof LayoutTicketingStepsStepIdRoute
  LayoutAccommodationsIndexRoute: typeof LayoutAccommodationsIndexRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutApplicationsIndexRoute: typeof LayoutApplicationsIndexRoute
  LayoutAttendeesIndexRoute: typeof LayoutAttendeesIndexRoute
  LayoutCouponsIndexRoute: typeof LayoutCouponsIndexRoute
  LayoutEmailTemplatesIndexRoute: typeof LayoutEmailTemplatesIndexRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
  LayoutFormBuilderIndexRoute: typeof LayoutFormBuilderIndexRoute
  LayoutGroupsIndexRoute: typeof LayoutGroupsIndexRoute
  LayoutHumansIndexRoute: typeof LayoutHumansIndexRoute
  LayoutInvitesIndexRoute: typeof LayoutInvitesIndexRoute
  LayoutOrganizationsIndexRoute: typeof LayoutOrganizationsIndexRoute
  LayoutPopupsIndexRoute: typeof LayoutPopupsIndexRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
  LayoutReferralsIndexRoute: typeof LayoutReferralsIndexRoute
  LayoutSalesFlowsIndexRoute: typeof LayoutSalesFlowsIndexRoute
  LayoutTasksIndexRoute: typeof LayoutTasksIndexRoute
  LayoutThemeIndexRoute: typeof LayoutThemeIndexRoute
  LayoutTicketingStepsIndexRoute: typeof LayoutTicketingStepsIndexRoute
  LayoutAccommodationsRoomsNewRoute: typeof LayoutAccommodationsRoomsNewRoute
  LayoutAdminIdEditRoute: typeof LayoutAdminIdEditRoute
  LayoutCouponsIdEditRoute: typeof LayoutCouponsIdEditRoute
  LayoutEmailTemplatesTypeEditRoute: typeof LayoutEmailTemplatesTypeEditRoute
  LayoutEventsEventIdEditRoute: typeof LayoutEventsEventIdEditRoute
  LayoutEventsTracksNewRoute: typeof LayoutEventsTracksNewRoute
  LayoutEventsVenuesNewRoute: typeof LayoutEventsVenuesNewRoute
  LayoutFormBuilderIdEditRoute: typeof LayoutFormBuilderIdEditRoute
  LayoutFormBuilderSectionsNewRoute: typeof LayoutFormBuilderSectionsNewRoute
  LayoutGroupsIdEditRoute: typeof LayoutGroupsIdEditRoute
  LayoutInvitesInviteIdEditRoute: typeof LayoutInvitesInviteIdEditRoute
  LayoutOrganizationsIdEditRoute: typeof LayoutOrganizationsIdEditRoute
  LayoutPopupsIdBulkGrantRoute: typeof LayoutPopupsIdBulkGrantRoute
  LayoutPopupsIdEditRoute: typeof LayoutPopupsIdEditRoute
  LayoutProductsIdEditRoute: typeof LayoutProductsIdEditRoute
  LayoutSalesFlowsIdEditRoute: typeof LayoutSalesFlowsIdEditRoute
  LayoutEventsTracksIndexRoute: typeof LayoutEventsTracksIndexRoute
  LayoutEventsVenuesIndexRoute: typeof LayoutEventsVenuesIndexRoute
  LayoutAccommodationsRoomsIdEditRoute: typeof LayoutAccommodationsRoomsIdEditRoute
  LayoutEventsTracksTrackIdEditRoute: typeof LayoutEventsTracksTrackIdEditRoute
  LayoutEventsVenuesVenueIdEditRoute: typeof LayoutEventsVenuesVenueIdEditRoute
  LayoutEventsVenuesVenueIdScheduleRoute: typeof LayoutEventsVenuesVenueIdScheduleRoute
  LayoutFormBuilderSectionsIdEditRoute: typeof LayoutFormBuilderSectionsIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAbandonedCartsRoute: LayoutAbandonedCartsRoute,
  LayoutActivityRoute: LayoutActivityRoute,
  LayoutApiKeysRoute: LayoutApiKeysRoute,
  LayoutCheckInRoute: LayoutCheckInRoute,
  LayoutEmailLogsRoute: LayoutEmailLogsRoute,
  LayoutOnboardingRoute: LayoutOnboardingRoute,
  LayoutPaymentsRoute: LayoutPaymentsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutThirdPartyAppsRoute: LayoutThirdPartyAppsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminNewRoute: LayoutAdminNewRoute,
  LayoutApplicationsIdRoute: LayoutApplicationsIdRoute,
  LayoutApplicationsReviewQueueRoute: LayoutApplicationsReviewQueueRoute,
  LayoutAttendeesAttendeeIdRoute: LayoutAttendeesAttendeeIdRoute,
  LayoutCouponsNewRoute: LayoutCouponsNewRoute,
  LayoutEventsEventIdRoute: LayoutEventsEventIdRoute,
  LayoutEventsDayByVenueRoute: LayoutEventsDayByVenueRoute,
  LayoutEventsNewRoute: LayoutEventsNewRoute,
  LayoutEventsPropertiesRoute: LayoutEventsPropertiesRoute,
  LayoutEventsSettingsRoute: LayoutEventsSettingsRoute,
  LayoutFormBuilderNewRoute: LayoutFormBuilderNewRoute,
  LayoutGroupsNewRoute: LayoutGroupsNewRoute,
  LayoutHumansIdRoute: LayoutHumansIdRoute,
  LayoutInvitesNewRoute: LayoutInvitesNewRoute,
  LayoutOrganizationsNewRoute: LayoutOrganizationsNewRoute,
  LayoutPopupsNewRoute: LayoutPopupsNewRoute,
  LayoutProductsNewRoute: LayoutProductsNewRoute,
  LayoutSalesFlowsNewRoute: LayoutSalesFlowsNewRoute,
  LayoutTicketingStepsStepIdRoute: LayoutTicketingStepsStepIdRoute,
  LayoutAccommodationsIndexRoute: LayoutAccommodationsIndexRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutApplicationsIndexRoute: LayoutApplicationsIndexRoute,
  LayoutAttendeesIndexRoute: LayoutAttendeesIndexRoute,
  LayoutCouponsIndexRoute: LayoutCouponsIndexRoute,
  LayoutEmailTemplatesIndexRoute: LayoutEmailTemplatesIndexRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
  LayoutFormBuilderIndexRoute: LayoutFormBuilderIndexRoute,
  LayoutGroupsIndexRoute: LayoutGroupsIndexRoute,
  LayoutHumansIndexRoute: LayoutHumansIndexRoute,
  LayoutInvitesIndexRoute: LayoutInvitesIndexRoute,
  LayoutOrganizationsIndexRoute: LayoutOrganizationsIndexRoute,
  LayoutPopupsIndexRoute: LayoutPopupsIndexRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
  LayoutReferralsIndexRoute: LayoutReferralsIndexRoute,
  LayoutSalesFlowsIndexRoute: LayoutSalesFlowsIndexRoute,
  LayoutTasksIndexRoute: LayoutTasksIndexRoute,
  LayoutThemeIndexRoute: LayoutThemeIndexRoute,
  LayoutTicketingStepsIndexRoute: LayoutTicketingStepsIndexRoute,
  LayoutAccommodationsRoomsNewRoute: LayoutAccommodationsRoomsNewRoute,
  LayoutAdminIdEditRoute: LayoutAdminIdEditRoute,
  LayoutCouponsIdEditRoute: LayoutCouponsIdEditRoute,
  LayoutEmailTemplatesTypeEditRoute: LayoutEmailTemplatesTypeEditRoute,
  LayoutEventsEventIdEditRoute: LayoutEventsEventIdEditRoute,
  LayoutEventsTracksNewRoute: LayoutEventsTracksNewRoute,
  LayoutEventsVenuesNewRoute: LayoutEventsVenuesNewRoute,
  LayoutFormBuilderIdEditRoute: LayoutFormBuilderIdEditRoute,
  LayoutFormBuilderSectionsNewRoute: LayoutFormBuilderSectionsNewRoute,
  LayoutGroupsIdEditRoute: LayoutGroupsIdEditRoute,
  LayoutInvitesInviteIdEditRoute: LayoutInvitesInviteIdEditRoute,
  LayoutOrganizationsIdEditRoute: LayoutOrganizationsIdEditRoute,
  LayoutPopupsIdBulkGrantRoute: LayoutPopupsIdBulkGrantRoute,
  LayoutPopupsIdEditRoute: LayoutPopupsIdEditRoute,
  LayoutProductsIdEditRoute: LayoutProductsIdEditRoute,
  LayoutSalesFlowsIdEditRoute: LayoutSalesFlowsIdEditRoute,
  LayoutEventsTracksIndexRoute: LayoutEventsTracksIndexRoute,
  LayoutEventsVenuesIndexRoute: LayoutEventsVenuesIndexRoute,
  LayoutAccommodationsRoomsIdEditRoute: LayoutAccommodationsRoomsIdEditRoute,
  LayoutEventsTracksTrackIdEditRoute: LayoutEventsTracksTrackIdEditRoute,
  LayoutEventsVenuesVenueIdEditRoute: LayoutEventsVenuesVenueIdEditRoute,
  LayoutEventsVenuesVenueIdScheduleRoute:
    LayoutEventsVenuesVenueIdScheduleRoute,
  LayoutFormBuilderSectionsIdEditRoute: LayoutFormBuilderSectionsIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
