/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout/payments'
import { Route as LayoutAttendeesRouteImport } from './routes/_layout/attendees'
import { Route as LayoutAbandonedCartsRouteImport } from './routes/_layout/abandoned-carts'
import { Route as LayoutTicketingStepsIndexRouteImport } from './routes/_layout/ticketing-steps/index'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout/products/index'
import { Route as LayoutPopupsIndexRouteImport } from './routes/_layout/popups/index'
import { Route as LayoutOrganizationsIndexRouteImport } from './routes/_layout/organizations/index'
import { Route as LayoutHumansIndexRouteImport } from './routes/_layout/humans/index'
import { Route as LayoutGroupsIndexRouteImport } from './routes/_layout/groups/index'
import { Route as LayoutFormBuilderIndexRouteImport } from './routes/_layout/form-builder/index'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutEmailTemplatesIndexRouteImport } from './routes/_layout/email-templates/index'
import { Route as LayoutCouponsIndexRouteImport } from './routes/_layout/coupons/index'
import { Route as LayoutApplicationsIndexRouteImport } from './routes/_layout/applications/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutTicketingStepsStepIdRouteImport } from './routes/_layout/ticketing-steps/$stepId'
import { Route as LayoutProductsNewRouteImport } from './routes/_layout/products/new'
import { Route as LayoutPopupsNewRouteImport } from './routes/_layout/popups/new'
import { Route as LayoutOrganizationsNewRouteImport } from './routes/_layout/organizations/new'
import { Route as LayoutHumansNewRouteImport } from './routes/_layout/humans/new'
import { Route as LayoutGroupsNewRouteImport } from './routes/_layout/groups/new'
import { Route as LayoutFormBuilderNewRouteImport } from './routes/_layout/form-builder/new'
import { Route as LayoutEventsVenuesScheduleRouteImport } from './routes/_layout/events/venues-schedule'
import { Route as LayoutEventsVenuesNewRouteImport } from './routes/_layout/events/venues-new'
import { Route as LayoutEventsVenuesEditRouteImport } from './routes/_layout/events/venues-edit'
import { Route as LayoutEventsVenuesRouteImport } from './routes/_layout/events/venues'
import { Route as LayoutEventsSettingsRouteImport } from './routes/_layout/events/settings'
import { Route as LayoutEventsPropertiesRouteImport } from './routes/_layout/events/properties'
import { Route as LayoutEventsNewRouteImport } from './routes/_layout/events/new'
import { Route as LayoutCouponsNewRouteImport } from './routes/_layout/coupons/new'
import { Route as LayoutApplicationsReviewQueueRouteImport } from './routes/_layout/applications/review-queue'
import { Route as LayoutApplicationsNewRouteImport } from './routes/_layout/applications/new'
import { Route as LayoutApplicationsIdRouteImport } from './routes/_layout/applications/$id'
import { Route as LayoutAdminNewRouteImport } from './routes/_layout/admin/new'
import { Route as LayoutEventsTracksIndexRouteImport } from './routes/_layout/events/tracks/index'
import { Route as LayoutProductsIdEditRouteImport } from './routes/_layout/products/$id.edit'
import { Route as LayoutPopupsIdEditRouteImport } from './routes/_layout/popups/$id.edit'
import { Route as LayoutOrganizationsIdEditRouteImport } from './routes/_layout/organizations/$id.edit'
import { Route as LayoutHumansIdEditRouteImport } from './routes/_layout/humans/$id.edit'
import { Route as LayoutGroupsIdEditRouteImport } from './routes/_layout/groups/$id.edit'
import { Route as LayoutFormBuilderSectionsNewRouteImport } from './routes/_layout/form-builder/sections/new'
import { Route as LayoutFormBuilderIdEditRouteImport } from './routes/_layout/form-builder/$id.edit'
import { Route as LayoutEventsTracksNewRouteImport } from './routes/_layout/events/tracks/new'
import { Route as LayoutEventsEventIdEditRouteImport } from './routes/_layout/events/$eventId.edit'
import { Route as LayoutEmailTemplatesTypeEditRouteImport } from './routes/_layout/email-templates/$type.edit'
import { Route as LayoutCouponsIdEditRouteImport } from './routes/_layout/coupons/$id.edit'
import { Route as LayoutAdminIdEditRouteImport } from './routes/_layout/admin/$id.edit'
import { Route as LayoutFormBuilderSectionsIdEditRouteImport } from './routes/_layout/form-builder/sections/$id.edit'
import { Route as LayoutEventsTracksTrackIdEditRouteImport } from './routes/_layout/events/tracks/$trackId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendeesRoute = LayoutAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAbandonedCartsRoute = LayoutAbandonedCartsRouteImport.update({
  id: '/abandoned-carts',
  path: '/abandoned-carts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketingStepsIndexRoute =
  LayoutTicketingStepsIndexRouteImport.update({
    id: '/ticketing-steps/',
    path: '/ticketing-steps/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIndexRoute = LayoutPopupsIndexRouteImport.update({
  id: '/popups/',
  path: '/popups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsIndexRoute =
  LayoutOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHumansIndexRoute = LayoutHumansIndexRouteImport.update({
  id: '/humans/',
  path: '/humans/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIndexRoute = LayoutGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderIndexRoute = LayoutFormBuilderIndexRouteImport.update({
  id: '/form-builder/',
  path: '/form-builder/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailTemplatesIndexRoute =
  LayoutEmailTemplatesIndexRouteImport.update({
    id: '/email-templates/',
    path: '/email-templates/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCouponsIndexRoute = LayoutCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsIndexRoute = LayoutApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTicketingStepsStepIdRoute =
  LayoutTicketingStepsStepIdRouteImport.update({
    id: '/ticketing-steps/$stepId',
    path: '/ticketing-steps/$stepId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProductsNewRoute = LayoutProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsNewRoute = LayoutPopupsNewRouteImport.update({
  id: '/popups/new',
  path: '/popups/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsNewRoute = LayoutOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHumansNewRoute = LayoutHumansNewRouteImport.update({
  id: '/humans/new',
  path: '/humans/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsNewRoute = LayoutGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderNewRoute = LayoutFormBuilderNewRouteImport.update({
  id: '/form-builder/new',
  path: '/form-builder/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsVenuesScheduleRoute =
  LayoutEventsVenuesScheduleRouteImport.update({
    id: '/events/venues-schedule',
    path: '/events/venues-schedule',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEventsVenuesNewRoute = LayoutEventsVenuesNewRouteImport.update({
  id: '/events/venues-new',
  path: '/events/venues-new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsVenuesEditRoute = LayoutEventsVenuesEditRouteImport.update({
  id: '/events/venues-edit',
  path: '/events/venues-edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsVenuesRoute = LayoutEventsVenuesRouteImport.update({
  id: '/events/venues',
  path: '/events/venues',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsSettingsRoute = LayoutEventsSettingsRouteImport.update({
  id: '/events/settings',
  path: '/events/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsPropertiesRoute = LayoutEventsPropertiesRouteImport.update({
  id: '/events/properties',
  path: '/events/properties',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsNewRoute = LayoutEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCouponsNewRoute = LayoutCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsReviewQueueRoute =
  LayoutApplicationsReviewQueueRouteImport.update({
    id: '/applications/review-queue',
    path: '/applications/review-queue',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApplicationsNewRoute = LayoutApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsIdRoute = LayoutApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminNewRoute = LayoutAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsTracksIndexRoute = LayoutEventsTracksIndexRouteImport.update({
  id: '/events/tracks/',
  path: '/events/tracks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsIdEditRoute = LayoutProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPopupsIdEditRoute = LayoutPopupsIdEditRouteImport.update({
  id: '/popups/$id/edit',
  path: '/popups/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsIdEditRoute =
  LayoutOrganizationsIdEditRouteImport.update({
    id: '/organizations/$id/edit',
    path: '/organizations/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutHumansIdEditRoute = LayoutHumansIdEditRouteImport.update({
  id: '/humans/$id/edit',
  path: '/humans/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsIdEditRoute = LayoutGroupsIdEditRouteImport.update({
  id: '/groups/$id/edit',
  path: '/groups/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderSectionsNewRoute =
  LayoutFormBuilderSectionsNewRouteImport.update({
    id: '/form-builder/sections/new',
    path: '/form-builder/sections/new',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFormBuilderIdEditRoute = LayoutFormBuilderIdEditRouteImport.update({
  id: '/form-builder/$id/edit',
  path: '/form-builder/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsTracksNewRoute = LayoutEventsTracksNewRouteImport.update({
  id: '/events/tracks/new',
  path: '/events/tracks/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsEventIdEditRoute = LayoutEventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailTemplatesTypeEditRoute =
  LayoutEmailTemplatesTypeEditRouteImport.update({
    id: '/email-templates/$type/edit',
    path: '/email-templates/$type/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCouponsIdEditRoute = LayoutCouponsIdEditRouteImport.update({
  id: '/coupons/$id/edit',
  path: '/coupons/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIdEditRoute = LayoutAdminIdEditRouteImport.update({
  id: '/admin/$id/edit',
  path: '/admin/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormBuilderSectionsIdEditRoute =
  LayoutFormBuilderSectionsIdEditRouteImport.update({
    id: '/form-builder/sections/$id/edit',
    path: '/form-builder/sections/$id/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEventsTracksTrackIdEditRoute =
  LayoutEventsTracksTrackIdEditRouteImport.update({
    id: '/events/tracks/$trackId/edit',
    path: '/events/tracks/$trackId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/abandoned-carts': typeof LayoutAbandonedCartsRoute
  '/attendees': typeof LayoutAttendeesRoute
  '/payments': typeof LayoutPaymentsRoute
  '/settings': typeof LayoutSettingsRoute
  '/admin/new': typeof LayoutAdminNewRoute
  '/applications/$id': typeof LayoutApplicationsIdRoute
  '/applications/new': typeof LayoutApplicationsNewRoute
  '/applications/review-queue': typeof LayoutApplicationsReviewQueueRoute
  '/coupons/new': typeof LayoutCouponsNewRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/events/properties': typeof LayoutEventsPropertiesRoute
  '/events/settings': typeof LayoutEventsSettingsRoute
  '/events/venues': typeof LayoutEventsVenuesRoute
  '/events/venues-edit': typeof LayoutEventsVenuesEditRoute
  '/events/venues-new': typeof LayoutEventsVenuesNewRoute
  '/events/venues-schedule': typeof LayoutEventsVenuesScheduleRoute
  '/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/groups/new': typeof LayoutGroupsNewRoute
  '/humans/new': typeof LayoutHumansNewRoute
  '/organizations/new': typeof LayoutOrganizationsNewRoute
  '/popups/new': typeof LayoutPopupsNewRoute
  '/products/new': typeof LayoutProductsNewRoute
  '/ticketing-steps/$stepId': typeof LayoutTicketingStepsStepIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/applications/': typeof LayoutApplicationsIndexRoute
  '/coupons/': typeof LayoutCouponsIndexRoute
  '/email-templates/': typeof LayoutEmailTemplatesIndexRoute
  '/events/': typeof LayoutEventsIndexRoute
  '/form-builder/': typeof LayoutFormBuilderIndexRoute
  '/groups/': typeof LayoutGroupsIndexRoute
  '/humans/': typeof LayoutHumansIndexRoute
  '/organizations/': typeof LayoutOrganizationsIndexRoute
  '/popups/': typeof LayoutPopupsIndexRoute
  '/products/': typeof LayoutProductsIndexRoute
  '/ticketing-steps/': typeof LayoutTicketingStepsIndexRoute
  '/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/email-templates/$type/edit': typeof LayoutEmailTemplatesTypeEditRoute
  '/events/$eventId/edit': typeof LayoutEventsEventIdEditRoute
  '/events/tracks/new': typeof LayoutEventsTracksNewRoute
  '/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/form-builder/sections/new': typeof LayoutFormBuilderSectionsNewRoute
  '/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/humans/$id/edit': typeof LayoutHumansIdEditRoute
  '/organizations/$id/edit': typeof LayoutOrganizationsIdEditRoute
  '/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/events/tracks/': typeof LayoutEventsTracksIndexRoute
  '/events/tracks/$trackId/edit': typeof LayoutEventsTracksTrackIdEditRoute
  '/form-builder/sections/$id/edit': typeof LayoutFormBuilderSectionsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/abandoned-carts': typeof LayoutAbandonedCartsRoute
  '/attendees': typeof LayoutAttendeesRoute
  '/payments': typeof LayoutPaymentsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/new': typeof LayoutAdminNewRoute
  '/applications/$id': typeof LayoutApplicationsIdRoute
  '/applications/new': typeof LayoutApplicationsNewRoute
  '/applications/review-queue': typeof LayoutApplicationsReviewQueueRoute
  '/coupons/new': typeof LayoutCouponsNewRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/events/properties': typeof LayoutEventsPropertiesRoute
  '/events/settings': typeof LayoutEventsSettingsRoute
  '/events/venues': typeof LayoutEventsVenuesRoute
  '/events/venues-edit': typeof LayoutEventsVenuesEditRoute
  '/events/venues-new': typeof LayoutEventsVenuesNewRoute
  '/events/venues-schedule': typeof LayoutEventsVenuesScheduleRoute
  '/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/groups/new': typeof LayoutGroupsNewRoute
  '/humans/new': typeof LayoutHumansNewRoute
  '/organizations/new': typeof LayoutOrganizationsNewRoute
  '/popups/new': typeof LayoutPopupsNewRoute
  '/products/new': typeof LayoutProductsNewRoute
  '/ticketing-steps/$stepId': typeof LayoutTicketingStepsStepIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/applications': typeof LayoutApplicationsIndexRoute
  '/coupons': typeof LayoutCouponsIndexRoute
  '/email-templates': typeof LayoutEmailTemplatesIndexRoute
  '/events': typeof LayoutEventsIndexRoute
  '/form-builder': typeof LayoutFormBuilderIndexRoute
  '/groups': typeof LayoutGroupsIndexRoute
  '/humans': typeof LayoutHumansIndexRoute
  '/organizations': typeof LayoutOrganizationsIndexRoute
  '/popups': typeof LayoutPopupsIndexRoute
  '/products': typeof LayoutProductsIndexRoute
  '/ticketing-steps': typeof LayoutTicketingStepsIndexRoute
  '/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/email-templates/$type/edit': typeof LayoutEmailTemplatesTypeEditRoute
  '/events/$eventId/edit': typeof LayoutEventsEventIdEditRoute
  '/events/tracks/new': typeof LayoutEventsTracksNewRoute
  '/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/form-builder/sections/new': typeof LayoutFormBuilderSectionsNewRoute
  '/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/humans/$id/edit': typeof LayoutHumansIdEditRoute
  '/organizations/$id/edit': typeof LayoutOrganizationsIdEditRoute
  '/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/events/tracks': typeof LayoutEventsTracksIndexRoute
  '/events/tracks/$trackId/edit': typeof LayoutEventsTracksTrackIdEditRoute
  '/form-builder/sections/$id/edit': typeof LayoutFormBuilderSectionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/abandoned-carts': typeof LayoutAbandonedCartsRoute
  '/_layout/attendees': typeof LayoutAttendeesRoute
  '/_layout/payments': typeof LayoutPaymentsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/new': typeof LayoutAdminNewRoute
  '/_layout/applications/$id': typeof LayoutApplicationsIdRoute
  '/_layout/applications/new': typeof LayoutApplicationsNewRoute
  '/_layout/applications/review-queue': typeof LayoutApplicationsReviewQueueRoute
  '/_layout/coupons/new': typeof LayoutCouponsNewRoute
  '/_layout/events/new': typeof LayoutEventsNewRoute
  '/_layout/events/properties': typeof LayoutEventsPropertiesRoute
  '/_layout/events/settings': typeof LayoutEventsSettingsRoute
  '/_layout/events/venues': typeof LayoutEventsVenuesRoute
  '/_layout/events/venues-edit': typeof LayoutEventsVenuesEditRoute
  '/_layout/events/venues-new': typeof LayoutEventsVenuesNewRoute
  '/_layout/events/venues-schedule': typeof LayoutEventsVenuesScheduleRoute
  '/_layout/form-builder/new': typeof LayoutFormBuilderNewRoute
  '/_layout/groups/new': typeof LayoutGroupsNewRoute
  '/_layout/humans/new': typeof LayoutHumansNewRoute
  '/_layout/organizations/new': typeof LayoutOrganizationsNewRoute
  '/_layout/popups/new': typeof LayoutPopupsNewRoute
  '/_layout/products/new': typeof LayoutProductsNewRoute
  '/_layout/ticketing-steps/$stepId': typeof LayoutTicketingStepsStepIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/applications/': typeof LayoutApplicationsIndexRoute
  '/_layout/coupons/': typeof LayoutCouponsIndexRoute
  '/_layout/email-templates/': typeof LayoutEmailTemplatesIndexRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
  '/_layout/form-builder/': typeof LayoutFormBuilderIndexRoute
  '/_layout/groups/': typeof LayoutGroupsIndexRoute
  '/_layout/humans/': typeof LayoutHumansIndexRoute
  '/_layout/organizations/': typeof LayoutOrganizationsIndexRoute
  '/_layout/popups/': typeof LayoutPopupsIndexRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
  '/_layout/ticketing-steps/': typeof LayoutTicketingStepsIndexRoute
  '/_layout/admin/$id/edit': typeof LayoutAdminIdEditRoute
  '/_layout/coupons/$id/edit': typeof LayoutCouponsIdEditRoute
  '/_layout/email-templates/$type/edit': typeof LayoutEmailTemplatesTypeEditRoute
  '/_layout/events/$eventId/edit': typeof LayoutEventsEventIdEditRoute
  '/_layout/events/tracks/new': typeof LayoutEventsTracksNewRoute
  '/_layout/form-builder/$id/edit': typeof LayoutFormBuilderIdEditRoute
  '/_layout/form-builder/sections/new': typeof LayoutFormBuilderSectionsNewRoute
  '/_layout/groups/$id/edit': typeof LayoutGroupsIdEditRoute
  '/_layout/humans/$id/edit': typeof LayoutHumansIdEditRoute
  '/_layout/organizations/$id/edit': typeof LayoutOrganizationsIdEditRoute
  '/_layout/popups/$id/edit': typeof LayoutPopupsIdEditRoute
  '/_layout/products/$id/edit': typeof LayoutProductsIdEditRoute
  '/_layout/events/tracks/': typeof LayoutEventsTracksIndexRoute
  '/_layout/events/tracks/$trackId/edit': typeof LayoutEventsTracksTrackIdEditRoute
  '/_layout/form-builder/sections/$id/edit': typeof LayoutFormBuilderSectionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/abandoned-carts'
    | '/attendees'
    | '/payments'
    | '/settings'
    | '/admin/new'
    | '/applications/$id'
    | '/applications/new'
    | '/applications/review-queue'
    | '/coupons/new'
    | '/events/new'
    | '/events/properties'
    | '/events/settings'
    | '/events/venues'
    | '/events/venues-edit'
    | '/events/venues-new'
    | '/events/venues-schedule'
    | '/form-builder/new'
    | '/groups/new'
    | '/humans/new'
    | '/organizations/new'
    | '/popups/new'
    | '/products/new'
    | '/ticketing-steps/$stepId'
    | '/admin/'
    | '/applications/'
    | '/coupons/'
    | '/email-templates/'
    | '/events/'
    | '/form-builder/'
    | '/groups/'
    | '/humans/'
    | '/organizations/'
    | '/popups/'
    | '/products/'
    | '/ticketing-steps/'
    | '/admin/$id/edit'
    | '/coupons/$id/edit'
    | '/email-templates/$type/edit'
    | '/events/$eventId/edit'
    | '/events/tracks/new'
    | '/form-builder/$id/edit'
    | '/form-builder/sections/new'
    | '/groups/$id/edit'
    | '/humans/$id/edit'
    | '/organizations/$id/edit'
    | '/popups/$id/edit'
    | '/products/$id/edit'
    | '/events/tracks/'
    | '/events/tracks/$trackId/edit'
    | '/form-builder/sections/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/abandoned-carts'
    | '/attendees'
    | '/payments'
    | '/settings'
    | '/'
    | '/admin/new'
    | '/applications/$id'
    | '/applications/new'
    | '/applications/review-queue'
    | '/coupons/new'
    | '/events/new'
    | '/events/properties'
    | '/events/settings'
    | '/events/venues'
    | '/events/venues-edit'
    | '/events/venues-new'
    | '/events/venues-schedule'
    | '/form-builder/new'
    | '/groups/new'
    | '/humans/new'
    | '/organizations/new'
    | '/popups/new'
    | '/products/new'
    | '/ticketing-steps/$stepId'
    | '/admin'
    | '/applications'
    | '/coupons'
    | '/email-templates'
    | '/events'
    | '/form-builder'
    | '/groups'
    | '/humans'
    | '/organizations'
    | '/popups'
    | '/products'
    | '/ticketing-steps'
    | '/admin/$id/edit'
    | '/coupons/$id/edit'
    | '/email-templates/$type/edit'
    | '/events/$eventId/edit'
    | '/events/tracks/new'
    | '/form-builder/$id/edit'
    | '/form-builder/sections/new'
    | '/groups/$id/edit'
    | '/humans/$id/edit'
    | '/organizations/$id/edit'
    | '/popups/$id/edit'
    | '/products/$id/edit'
    | '/events/tracks'
    | '/events/tracks/$trackId/edit'
    | '/form-builder/sections/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/abandoned-carts'
    | '/_layout/attendees'
    | '/_layout/payments'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/new'
    | '/_layout/applications/$id'
    | '/_layout/applications/new'
    | '/_layout/applications/review-queue'
    | '/_layout/coupons/new'
    | '/_layout/events/new'
    | '/_layout/events/properties'
    | '/_layout/events/settings'
    | '/_layout/events/venues'
    | '/_layout/events/venues-edit'
    | '/_layout/events/venues-new'
    | '/_layout/events/venues-schedule'
    | '/_layout/form-builder/new'
    | '/_layout/groups/new'
    | '/_layout/humans/new'
    | '/_layout/organizations/new'
    | '/_layout/popups/new'
    | '/_layout/products/new'
    | '/_layout/ticketing-steps/$stepId'
    | '/_layout/admin/'
    | '/_layout/applications/'
    | '/_layout/coupons/'
    | '/_layout/email-templates/'
    | '/_layout/events/'
    | '/_layout/form-builder/'
    | '/_layout/groups/'
    | '/_layout/humans/'
    | '/_layout/organizations/'
    | '/_layout/popups/'
    | '/_layout/products/'
    | '/_layout/ticketing-steps/'
    | '/_layout/admin/$id/edit'
    | '/_layout/coupons/$id/edit'
    | '/_layout/email-templates/$type/edit'
    | '/_layout/events/$eventId/edit'
    | '/_layout/events/tracks/new'
    | '/_layout/form-builder/$id/edit'
    | '/_layout/form-builder/sections/new'
    | '/_layout/groups/$id/edit'
    | '/_layout/humans/$id/edit'
    | '/_layout/organizations/$id/edit'
    | '/_layout/popups/$id/edit'
    | '/_layout/products/$id/edit'
    | '/_layout/events/tracks/'
    | '/_layout/events/tracks/$trackId/edit'
    | '/_layout/form-builder/sections/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendees': {
      id: '/_layout/attendees'
      path: '/attendees'
      fullPath: '/attendees'
      preLoaderRoute: typeof LayoutAttendeesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/abandoned-carts': {
      id: '/_layout/abandoned-carts'
      path: '/abandoned-carts'
      fullPath: '/abandoned-carts'
      preLoaderRoute: typeof LayoutAbandonedCartsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticketing-steps/': {
      id: '/_layout/ticketing-steps/'
      path: '/ticketing-steps'
      fullPath: '/ticketing-steps/'
      preLoaderRoute: typeof LayoutTicketingStepsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/': {
      id: '/_layout/popups/'
      path: '/popups'
      fullPath: '/popups/'
      preLoaderRoute: typeof LayoutPopupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations/': {
      id: '/_layout/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutOrganizationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/': {
      id: '/_layout/humans/'
      path: '/humans'
      fullPath: '/humans/'
      preLoaderRoute: typeof LayoutHumansIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/': {
      id: '/_layout/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof LayoutGroupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/': {
      id: '/_layout/form-builder/'
      path: '/form-builder'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof LayoutFormBuilderIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-templates/': {
      id: '/_layout/email-templates/'
      path: '/email-templates'
      fullPath: '/email-templates/'
      preLoaderRoute: typeof LayoutEmailTemplatesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/': {
      id: '/_layout/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof LayoutCouponsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/': {
      id: '/_layout/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof LayoutApplicationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ticketing-steps/$stepId': {
      id: '/_layout/ticketing-steps/$stepId'
      path: '/ticketing-steps/$stepId'
      fullPath: '/ticketing-steps/$stepId'
      preLoaderRoute: typeof LayoutTicketingStepsStepIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/new': {
      id: '/_layout/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof LayoutProductsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/new': {
      id: '/_layout/popups/new'
      path: '/popups/new'
      fullPath: '/popups/new'
      preLoaderRoute: typeof LayoutPopupsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations/new': {
      id: '/_layout/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutOrganizationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/new': {
      id: '/_layout/humans/new'
      path: '/humans/new'
      fullPath: '/humans/new'
      preLoaderRoute: typeof LayoutHumansNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/new': {
      id: '/_layout/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof LayoutGroupsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/new': {
      id: '/_layout/form-builder/new'
      path: '/form-builder/new'
      fullPath: '/form-builder/new'
      preLoaderRoute: typeof LayoutFormBuilderNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues-schedule': {
      id: '/_layout/events/venues-schedule'
      path: '/events/venues-schedule'
      fullPath: '/events/venues-schedule'
      preLoaderRoute: typeof LayoutEventsVenuesScheduleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues-new': {
      id: '/_layout/events/venues-new'
      path: '/events/venues-new'
      fullPath: '/events/venues-new'
      preLoaderRoute: typeof LayoutEventsVenuesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues-edit': {
      id: '/_layout/events/venues-edit'
      path: '/events/venues-edit'
      fullPath: '/events/venues-edit'
      preLoaderRoute: typeof LayoutEventsVenuesEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/venues': {
      id: '/_layout/events/venues'
      path: '/events/venues'
      fullPath: '/events/venues'
      preLoaderRoute: typeof LayoutEventsVenuesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/settings': {
      id: '/_layout/events/settings'
      path: '/events/settings'
      fullPath: '/events/settings'
      preLoaderRoute: typeof LayoutEventsSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/properties': {
      id: '/_layout/events/properties'
      path: '/events/properties'
      fullPath: '/events/properties'
      preLoaderRoute: typeof LayoutEventsPropertiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/new': {
      id: '/_layout/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof LayoutEventsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/new': {
      id: '/_layout/coupons/new'
      path: '/coupons/new'
      fullPath: '/coupons/new'
      preLoaderRoute: typeof LayoutCouponsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/review-queue': {
      id: '/_layout/applications/review-queue'
      path: '/applications/review-queue'
      fullPath: '/applications/review-queue'
      preLoaderRoute: typeof LayoutApplicationsReviewQueueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/new': {
      id: '/_layout/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof LayoutApplicationsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications/$id': {
      id: '/_layout/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof LayoutApplicationsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/new': {
      id: '/_layout/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof LayoutAdminNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/tracks/': {
      id: '/_layout/events/tracks/'
      path: '/events/tracks'
      fullPath: '/events/tracks/'
      preLoaderRoute: typeof LayoutEventsTracksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/$id/edit': {
      id: '/_layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof LayoutProductsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/popups/$id/edit': {
      id: '/_layout/popups/$id/edit'
      path: '/popups/$id/edit'
      fullPath: '/popups/$id/edit'
      preLoaderRoute: typeof LayoutPopupsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations/$id/edit': {
      id: '/_layout/organizations/$id/edit'
      path: '/organizations/$id/edit'
      fullPath: '/organizations/$id/edit'
      preLoaderRoute: typeof LayoutOrganizationsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/humans/$id/edit': {
      id: '/_layout/humans/$id/edit'
      path: '/humans/$id/edit'
      fullPath: '/humans/$id/edit'
      preLoaderRoute: typeof LayoutHumansIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups/$id/edit': {
      id: '/_layout/groups/$id/edit'
      path: '/groups/$id/edit'
      fullPath: '/groups/$id/edit'
      preLoaderRoute: typeof LayoutGroupsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/sections/new': {
      id: '/_layout/form-builder/sections/new'
      path: '/form-builder/sections/new'
      fullPath: '/form-builder/sections/new'
      preLoaderRoute: typeof LayoutFormBuilderSectionsNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/$id/edit': {
      id: '/_layout/form-builder/$id/edit'
      path: '/form-builder/$id/edit'
      fullPath: '/form-builder/$id/edit'
      preLoaderRoute: typeof LayoutFormBuilderIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/tracks/new': {
      id: '/_layout/events/tracks/new'
      path: '/events/tracks/new'
      fullPath: '/events/tracks/new'
      preLoaderRoute: typeof LayoutEventsTracksNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/$eventId/edit': {
      id: '/_layout/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof LayoutEventsEventIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-templates/$type/edit': {
      id: '/_layout/email-templates/$type/edit'
      path: '/email-templates/$type/edit'
      fullPath: '/email-templates/$type/edit'
      preLoaderRoute: typeof LayoutEmailTemplatesTypeEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/coupons/$id/edit': {
      id: '/_layout/coupons/$id/edit'
      path: '/coupons/$id/edit'
      fullPath: '/coupons/$id/edit'
      preLoaderRoute: typeof LayoutCouponsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/$id/edit': {
      id: '/_layout/admin/$id/edit'
      path: '/admin/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof LayoutAdminIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-builder/sections/$id/edit': {
      id: '/_layout/form-builder/sections/$id/edit'
      path: '/form-builder/sections/$id/edit'
      fullPath: '/form-builder/sections/$id/edit'
      preLoaderRoute: typeof LayoutFormBuilderSectionsIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/tracks/$trackId/edit': {
      id: '/_layout/events/tracks/$trackId/edit'
      path: '/events/tracks/$trackId/edit'
      fullPath: '/events/tracks/$trackId/edit'
      preLoaderRoute: typeof LayoutEventsTracksTrackIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAbandonedCartsRoute: typeof LayoutAbandonedCartsRoute
  LayoutAttendeesRoute: typeof LayoutAttendeesRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminNewRoute: typeof LayoutAdminNewRoute
  LayoutApplicationsIdRoute: typeof LayoutApplicationsIdRoute
  LayoutApplicationsNewRoute: typeof LayoutApplicationsNewRoute
  LayoutApplicationsReviewQueueRoute: typeof LayoutApplicationsReviewQueueRoute
  LayoutCouponsNewRoute: typeof LayoutCouponsNewRoute
  LayoutEventsNewRoute: typeof LayoutEventsNewRoute
  LayoutEventsPropertiesRoute: typeof LayoutEventsPropertiesRoute
  LayoutEventsSettingsRoute: typeof LayoutEventsSettingsRoute
  LayoutEventsVenuesRoute: typeof LayoutEventsVenuesRoute
  LayoutEventsVenuesEditRoute: typeof LayoutEventsVenuesEditRoute
  LayoutEventsVenuesNewRoute: typeof LayoutEventsVenuesNewRoute
  LayoutEventsVenuesScheduleRoute: typeof LayoutEventsVenuesScheduleRoute
  LayoutFormBuilderNewRoute: typeof LayoutFormBuilderNewRoute
  LayoutGroupsNewRoute: typeof LayoutGroupsNewRoute
  LayoutHumansNewRoute: typeof LayoutHumansNewRoute
  LayoutOrganizationsNewRoute: typeof LayoutOrganizationsNewRoute
  LayoutPopupsNewRoute: typeof LayoutPopupsNewRoute
  LayoutProductsNewRoute: typeof LayoutProductsNewRoute
  LayoutTicketingStepsStepIdRoute: typeof LayoutTicketingStepsStepIdRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutApplicationsIndexRoute: typeof LayoutApplicationsIndexRoute
  LayoutCouponsIndexRoute: typeof LayoutCouponsIndexRoute
  LayoutEmailTemplatesIndexRoute: typeof LayoutEmailTemplatesIndexRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
  LayoutFormBuilderIndexRoute: typeof LayoutFormBuilderIndexRoute
  LayoutGroupsIndexRoute: typeof LayoutGroupsIndexRoute
  LayoutHumansIndexRoute: typeof LayoutHumansIndexRoute
  LayoutOrganizationsIndexRoute: typeof LayoutOrganizationsIndexRoute
  LayoutPopupsIndexRoute: typeof LayoutPopupsIndexRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
  LayoutTicketingStepsIndexRoute: typeof LayoutTicketingStepsIndexRoute
  LayoutAdminIdEditRoute: typeof LayoutAdminIdEditRoute
  LayoutCouponsIdEditRoute: typeof LayoutCouponsIdEditRoute
  LayoutEmailTemplatesTypeEditRoute: typeof LayoutEmailTemplatesTypeEditRoute
  LayoutEventsEventIdEditRoute: typeof LayoutEventsEventIdEditRoute
  LayoutEventsTracksNewRoute: typeof LayoutEventsTracksNewRoute
  LayoutFormBuilderIdEditRoute: typeof LayoutFormBuilderIdEditRoute
  LayoutFormBuilderSectionsNewRoute: typeof LayoutFormBuilderSectionsNewRoute
  LayoutGroupsIdEditRoute: typeof LayoutGroupsIdEditRoute
  LayoutHumansIdEditRoute: typeof LayoutHumansIdEditRoute
  LayoutOrganizationsIdEditRoute: typeof LayoutOrganizationsIdEditRoute
  LayoutPopupsIdEditRoute: typeof LayoutPopupsIdEditRoute
  LayoutProductsIdEditRoute: typeof LayoutProductsIdEditRoute
  LayoutEventsTracksIndexRoute: typeof LayoutEventsTracksIndexRoute
  LayoutEventsTracksTrackIdEditRoute: typeof LayoutEventsTracksTrackIdEditRoute
  LayoutFormBuilderSectionsIdEditRoute: typeof LayoutFormBuilderSectionsIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAbandonedCartsRoute: LayoutAbandonedCartsRoute,
  LayoutAttendeesRoute: LayoutAttendeesRoute,
  LayoutPaymentsRoute: LayoutPaymentsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminNewRoute: LayoutAdminNewRoute,
  LayoutApplicationsIdRoute: LayoutApplicationsIdRoute,
  LayoutApplicationsNewRoute: LayoutApplicationsNewRoute,
  LayoutApplicationsReviewQueueRoute: LayoutApplicationsReviewQueueRoute,
  LayoutCouponsNewRoute: LayoutCouponsNewRoute,
  LayoutEventsNewRoute: LayoutEventsNewRoute,
  LayoutEventsPropertiesRoute: LayoutEventsPropertiesRoute,
  LayoutEventsSettingsRoute: LayoutEventsSettingsRoute,
  LayoutEventsVenuesRoute: LayoutEventsVenuesRoute,
  LayoutEventsVenuesEditRoute: LayoutEventsVenuesEditRoute,
  LayoutEventsVenuesNewRoute: LayoutEventsVenuesNewRoute,
  LayoutEventsVenuesScheduleRoute: LayoutEventsVenuesScheduleRoute,
  LayoutFormBuilderNewRoute: LayoutFormBuilderNewRoute,
  LayoutGroupsNewRoute: LayoutGroupsNewRoute,
  LayoutHumansNewRoute: LayoutHumansNewRoute,
  LayoutOrganizationsNewRoute: LayoutOrganizationsNewRoute,
  LayoutPopupsNewRoute: LayoutPopupsNewRoute,
  LayoutProductsNewRoute: LayoutProductsNewRoute,
  LayoutTicketingStepsStepIdRoute: LayoutTicketingStepsStepIdRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutApplicationsIndexRoute: LayoutApplicationsIndexRoute,
  LayoutCouponsIndexRoute: LayoutCouponsIndexRoute,
  LayoutEmailTemplatesIndexRoute: LayoutEmailTemplatesIndexRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
  LayoutFormBuilderIndexRoute: LayoutFormBuilderIndexRoute,
  LayoutGroupsIndexRoute: LayoutGroupsIndexRoute,
  LayoutHumansIndexRoute: LayoutHumansIndexRoute,
  LayoutOrganizationsIndexRoute: LayoutOrganizationsIndexRoute,
  LayoutPopupsIndexRoute: LayoutPopupsIndexRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
  LayoutTicketingStepsIndexRoute: LayoutTicketingStepsIndexRoute,
  LayoutAdminIdEditRoute: LayoutAdminIdEditRoute,
  LayoutCouponsIdEditRoute: LayoutCouponsIdEditRoute,
  LayoutEmailTemplatesTypeEditRoute: LayoutEmailTemplatesTypeEditRoute,
  LayoutEventsEventIdEditRoute: LayoutEventsEventIdEditRoute,
  LayoutEventsTracksNewRoute: LayoutEventsTracksNewRoute,
  LayoutFormBuilderIdEditRoute: LayoutFormBuilderIdEditRoute,
  LayoutFormBuilderSectionsNewRoute: LayoutFormBuilderSectionsNewRoute,
  LayoutGroupsIdEditRoute: LayoutGroupsIdEditRoute,
  LayoutHumansIdEditRoute: LayoutHumansIdEditRoute,
  LayoutOrganizationsIdEditRoute: LayoutOrganizationsIdEditRoute,
  LayoutPopupsIdEditRoute: LayoutPopupsIdEditRoute,
  LayoutProductsIdEditRoute: LayoutProductsIdEditRoute,
  LayoutEventsTracksIndexRoute: LayoutEventsTracksIndexRoute,
  LayoutEventsTracksTrackIdEditRoute: LayoutEventsTracksTrackIdEditRoute,
  LayoutFormBuilderSectionsIdEditRoute: LayoutFormBuilderSectionsIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
