// This file is auto-generated by @hey-api/openapi-ts

/**
 * Application schema for admin creation.
 *
 * Admins can create applications on behalf of users and set any status.
 * If email is provided and human doesn't exist, a new Human record is created.
 * Companions (spouse/kids) can be added during initial submission.
 */
export type ApplicationAdminCreate = {
    popup_id: string;
    first_name: string;
    last_name: string;
    email: string;
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    referral?: (string | null);
    info_not_shared?: (Array<(string)> | null);
    custom_fields?: ({
    [key: string]: unknown;
} | null);
    status?: ApplicationStatus;
    group_id?: (string | null);
    companions?: (Array<CompanionCreate> | null);
};

/**
 * Application schema for admin updates (can set any status).
 */
export type ApplicationAdminUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    referral?: (string | null);
    info_not_shared?: (Array<(string)> | null);
    custom_fields?: ({
    [key: string]: unknown;
} | null);
    status?: (ApplicationStatus | null);
};

/**
 * Application schema for creation.
 *
 * Profile fields can be provided here and will update the Human record.
 * Companions (spouse/kids) can be added during initial submission.
 */
export type ApplicationCreate = {
    popup_id: string;
    first_name: string;
    last_name: string;
    email?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    referral?: (string | null);
    info_not_shared?: (Array<(string)> | null);
    custom_fields?: ({
    [key: string]: unknown;
} | null);
    status?: (UserSettableStatus | null);
    human_id?: (string | null);
    group_id?: (string | null);
    companions?: (Array<CompanionCreate> | null);
};

/**
 * Application schema for API responses.
 */
export type ApplicationPublic = {
    id: string;
    tenant_id: string;
    popup_id: string;
    human_id: string;
    group_id?: (string | null);
    referral?: (string | null);
    info_not_shared?: Array<(string)>;
    status: string;
    custom_fields?: {
        [key: string]: unknown;
    };
    custom_fields_schema?: ({
    [key: string]: unknown;
} | null);
    submitted_at?: (string | null);
    accepted_at?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    human?: (HumanPublic | null);
    attendees?: Array<AttendeePublic>;
    red_flag?: boolean;
    brings_spouse?: boolean;
    brings_kids?: boolean;
    kid_count?: number;
};

/**
 * Schema for submitting a review.
 */
export type ApplicationReviewCreate = {
    decision: ReviewDecision;
    notes?: (string | null);
};

/**
 * ApplicationReview schema for API responses.
 */
export type ApplicationReviewPublic = {
    id: string;
    application_id: string;
    reviewer_id: string;
    tenant_id: string;
    decision: ReviewDecision;
    notes?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    reviewer_email?: (string | null);
    reviewer_full_name?: (string | null);
};

/**
 * Statistics for applications.
 */
export type ApplicationStats = {
    total?: number;
    draft?: number;
    in_review?: number;
    accepted?: number;
    rejected?: number;
    withdrawn?: number;
};

/**
 * Status for applications.
 */
export type ApplicationStatus = 'draft' | 'in review' | 'rejected' | 'accepted' | 'withdrawn';

/**
 * Application schema for updates by the applicant.
 *
 * Profile fields will update the Human record.
 */
export type ApplicationUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    referral?: (string | null);
    info_not_shared?: (Array<(string)> | null);
    custom_fields?: ({
    [key: string]: unknown;
} | null);
    status?: (UserSettableStatus | null);
};

/**
 * Schema for creating an approval strategy.
 */
export type ApprovalStrategyCreate = {
    strategy_type?: ApprovalStrategyType;
    required_approvals?: number;
    accept_threshold?: number;
    reject_threshold?: number;
    strong_yes_weight?: number;
    yes_weight?: number;
    no_weight?: number;
    strong_no_weight?: number;
};

/**
 * ApprovalStrategy schema for API responses.
 */
export type ApprovalStrategyPublic = {
    id: string;
    popup_id: string;
    tenant_id: string;
    strategy_type: ApprovalStrategyType;
    required_approvals: number;
    accept_threshold: number;
    reject_threshold: number;
    strong_yes_weight: number;
    yes_weight: number;
    no_weight: number;
    strong_no_weight: number;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * Types of approval strategies.
 */
export type ApprovalStrategyType = 'auto_accept' | 'any_reviewer' | 'all_reviewers' | 'threshold' | 'weighted';

/**
 * Schema for updating an approval strategy.
 */
export type ApprovalStrategyUpdate = {
    strategy_type?: (ApprovalStrategyType | null);
    required_approvals?: (number | null);
    accept_threshold?: (number | null);
    reject_threshold?: (number | null);
    strong_yes_weight?: (number | null);
    yes_weight?: (number | null);
    no_weight?: (number | null);
    strong_no_weight?: (number | null);
};

/**
 * Attendee schema for creation (by user).
 */
export type AttendeeCreate = {
    name: string;
    category: string;
    email?: (string | null);
    gender?: (string | null);
};

/**
 * Attendee schema for API responses.
 */
export type AttendeePublic = {
    tenant_id: string;
    application_id: string;
    human_id?: (string | null);
    name: string;
    category: string;
    email?: (string | null);
    gender?: (string | null);
    check_in_code: string;
    poap_url?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    products?: Array<unknown>;
};

/**
 * Statistics for attendees.
 */
export type AttendeeStats = {
    total?: number;
    main?: number;
    spouse?: number;
    kid?: number;
};

/**
 * Attendee schema for updates.
 */
export type AttendeeUpdate = {
    name?: (string | null);
    email?: (string | null);
    gender?: (string | null);
};

/**
 * Attendee with ticket/product information.
 */
export type AttendeeWithTickets = {
    id: string;
    name: string;
    email: (string | null);
    category: string;
    check_in_code: string;
    popup_id: string;
    popup_name: string;
    popup_slug?: (string | null);
    products: Array<TicketProduct>;
};

/**
 * Response after successfully sending auth code.
 */
export type AuthCodeSentResponse = {
    message: string;
    email: string;
    expires_in_minutes?: number;
};

/**
 * Schema for creating companion attendees (spouse/kids) during application.
 *
 * Used when submitting an application with family members.
 * Category is restricted to spouse/kid (main is auto-created from applicant).
 */
export type CompanionCreate = {
    name: string;
    category: string;
    email?: (string | null);
    gender?: (string | null);
};

/**
 * Coupon schema for creation.
 */
export type CouponCreate = {
    popup_id: string;
    code: string;
    discount_value: number;
    max_uses?: (number | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: boolean;
};

/**
 * Coupon schema for API responses.
 */
export type CouponPublic = {
    tenant_id: string;
    popup_id: string;
    code: string;
    discount_value?: number;
    max_uses?: (number | null);
    current_uses?: number;
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: boolean;
    id: string;
};

/**
 * Coupon schema for updates.
 */
export type CouponUpdate = {
    code?: (string | null);
    discount_value?: (number | null);
    max_uses?: (number | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Schema for validating a coupon code.
 */
export type CouponValidate = {
    popup_id: string;
    code: string;
};

export type CredentialInfo = {
    credential_type: CredentialType;
    db_username: string;
    db_password: string;
};

export type CredentialType = 'crud' | 'readonly';

/**
 * Complete dashboard statistics.
 */
export type DashboardStats = {
    applications: ApplicationStats;
    attendees: AttendeeStats;
    payments: PaymentStats;
};

export type FormFieldCreate = {
    popup_id: string;
    name: string;
    label: string;
    field_type?: string;
    section?: (string | null);
    position?: number;
    required?: boolean;
    options?: (Array<(string)> | null);
    placeholder?: (string | null);
    help_text?: (string | null);
};

export type FormFieldPublic = {
    id: string;
    tenant_id: string;
    popup_id: string;
    name: string;
    label: string;
    field_type: string;
    section?: (string | null);
    position?: number;
    required?: boolean;
    options?: (Array<(string)> | null);
    placeholder?: (string | null);
    help_text?: (string | null);
};

export type FormFieldUpdate = {
    name?: (string | null);
    label?: (string | null);
    field_type?: (string | null);
    section?: (string | null);
    position?: (number | null);
    required?: (boolean | null);
    options?: (Array<(string)> | null);
    placeholder?: (string | null);
    help_text?: (string | null);
};

/**
 * Group schema for admin updates (full access).
 */
export type GroupAdminUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
    discount_percentage?: (number | string | null);
    max_members?: (number | null);
    welcome_message?: (string | null);
    is_ambassador_group?: (boolean | null);
    ambassador_id?: (string | null);
    whitelisted_emails?: (Array<(string)> | null);
};

/**
 * Group schema for creation.
 */
export type GroupCreate = {
    popup_id: string;
    name: string;
    slug?: (string | null);
    description?: (string | null);
    discount_percentage?: (number | string);
    max_members?: (number | null);
    welcome_message?: (string | null);
    is_ambassador_group?: boolean;
    ambassador_id?: (string | null);
    whitelisted_emails?: (Array<(string)> | null);
};

/**
 * Schema for batch member creation.
 */
export type GroupMemberBatch = {
    members: Array<GroupMemberCreate>;
    update_existing?: boolean;
};

/**
 * Schema for batch member result.
 */
export type GroupMemberBatchResult = {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    local_resident?: (boolean | null);
    products?: Array<unknown>;
    success: boolean;
    err_msg?: (string | null);
};

/**
 * Schema for adding a member to a group.
 */
export type GroupMemberCreate = {
    first_name: string;
    last_name: string;
    email: string;
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    local_resident?: (boolean | null);
};

/**
 * Schema for member response with products.
 */
export type GroupMemberPublic = {
    id: string;
    first_name: string;
    last_name: string;
    email: string;
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    local_resident?: (boolean | null);
    products?: Array<unknown>;
};

/**
 * Schema for updating a group member.
 */
export type GroupMemberUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    email?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    local_resident?: (boolean | null);
};

/**
 * Group schema for API responses.
 */
export type GroupPublic = {
    tenant_id: string;
    popup_id: string;
    name: string;
    slug: string;
    description?: (string | null);
    discount_percentage?: string;
    max_members?: (number | null);
    welcome_message?: (string | null);
    is_ambassador_group?: boolean;
    ambassador_id?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    whitelisted_emails?: Array<GroupWhitelistedEmailPublic>;
    is_open?: boolean;
};

/**
 * Group schema for updates (limited fields for leaders).
 */
export type GroupUpdate = {
    description?: (string | null);
    welcome_message?: (string | null);
    max_members?: (number | null);
};

/**
 * Schema for whitelisted email response.
 */
export type GroupWhitelistedEmailPublic = {
    id: string;
    email: string;
    created_at: string;
};

/**
 * Group with members list.
 */
export type GroupWithMembers = {
    tenant_id: string;
    popup_id: string;
    name: string;
    slug: string;
    description?: (string | null);
    discount_percentage?: string;
    max_members?: (number | null);
    welcome_message?: (string | null);
    is_ambassador_group?: boolean;
    ambassador_id?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    whitelisted_emails?: Array<GroupWhitelistedEmailPublic>;
    is_open?: boolean;
    members?: Array<GroupMemberPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Request to initiate human authentication.
 */
export type HumanAuth = {
    tenant_id: string;
    email: string;
    picture_url?: (string | null);
    red_flag?: boolean;
};

/**
 * Human schema for creation.
 */
export type HumanCreate = {
    email: string;
    first_name?: (string | null);
    last_name?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    picture_url?: (string | null);
};

/**
 * Human schema for API responses.
 */
export type HumanPublic = {
    id: string;
    tenant_id: string;
    email: string;
    first_name?: (string | null);
    last_name?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    picture_url?: (string | null);
    red_flag?: boolean;
};

/**
 * Human schema for profile updates.
 */
export type HumanUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    telegram?: (string | null);
    organization?: (string | null);
    role?: (string | null);
    gender?: (string | null);
    age?: (string | null);
    residence?: (string | null);
    picture_url?: (string | null);
    red_flag?: (boolean | null);
};

/**
 * Request to verify human authentication code.
 */
export type HumanVerify = {
    email: string;
    tenant_id: string;
    code: string;
};

export type ListModel = {
    results: Array<unknown>;
    paging: Paging;
};

export type ListModel_ApplicationPublic_ = {
    results: Array<ApplicationPublic>;
    paging: Paging;
};

export type ListModel_ApplicationReviewPublic_ = {
    results: Array<ApplicationReviewPublic>;
    paging: Paging;
};

export type ListModel_AttendeePublic_ = {
    results: Array<AttendeePublic>;
    paging: Paging;
};

export type ListModel_CouponPublic_ = {
    results: Array<CouponPublic>;
    paging: Paging;
};

export type ListModel_FormFieldPublic_ = {
    results: Array<FormFieldPublic>;
    paging: Paging;
};

export type ListModel_GroupPublic_ = {
    results: Array<GroupPublic>;
    paging: Paging;
};

export type ListModel_HumanPublic_ = {
    results: Array<HumanPublic>;
    paging: Paging;
};

export type ListModel_PaymentPublic_ = {
    results: Array<PaymentPublic>;
    paging: Paging;
};

export type ListModel_PopupPublic_ = {
    results: Array<PopupPublic>;
    paging: Paging;
};

export type ListModel_PopupReviewerPublic_ = {
    results: Array<PopupReviewerPublic>;
    paging: Paging;
};

export type ListModel_ProductPublic_ = {
    results: Array<ProductPublic>;
    paging: Paging;
};

export type ListModel_TenantPublic_ = {
    results: Array<TenantPublic>;
    paging: Paging;
};

export type ListModel_UserPublic_ = {
    results: Array<UserPublic>;
    paging: Paging;
};

export type Paging = {
    limit: number;
    offset: number;
    total: number;
};

/**
 * Schema for creating a payment.
 */
export type PaymentCreate = {
    application_id: string;
    products: Array<PaymentProductRequest>;
    coupon_code?: (string | null);
    edit_passes?: boolean;
};

/**
 * Schema for payment preview (before creating).
 */
export type PaymentPreview = {
    application_id: string;
    products: Array<PaymentProductRequest>;
    original_amount: string;
    amount: string;
    currency?: string;
    edit_passes?: boolean;
    coupon_id?: (string | null);
    coupon_code?: (string | null);
    discount_value?: (string | null);
    group_id?: (string | null);
    status?: (string | null);
    external_id?: (string | null);
    checkout_url?: (string | null);
};

/**
 * Product selection for payment.
 */
export type PaymentProductRequest = {
    product_id: string;
    attendee_id: string;
    quantity?: number;
};

/**
 * Payment product snapshot in response.
 */
export type PaymentProductResponse = {
    product_id: string;
    attendee_id: string;
    quantity: number;
    product_name: string;
    product_description?: (string | null);
    product_price: string;
    product_category: string;
    created_at: string;
};

/**
 * Payment schema for API responses.
 */
export type PaymentPublic = {
    tenant_id: string;
    application_id: string;
    external_id?: (string | null);
    status?: string;
    amount?: string;
    currency?: string;
    rate?: (string | null);
    source?: (string | null);
    checkout_url?: (string | null);
    coupon_id?: (string | null);
    coupon_code?: (string | null);
    discount_value?: (string | null);
    edit_passes?: boolean;
    group_id?: (string | null);
    id: string;
    products_snapshot?: Array<PaymentProductResponse>;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * Payment source/provider.
 */
export type PaymentSource = 'SimpleFI' | 'Stripe';

/**
 * Statistics for payments.
 */
export type PaymentStats = {
    total?: number;
    pending?: number;
    approved?: number;
    rejected?: number;
    expired?: number;
    cancelled?: number;
    total_revenue?: string;
    pending_revenue?: string;
    approved_revenue?: string;
    total_discounts?: string;
};

/**
 * Payment status.
 */
export type PaymentStatus = 'pending' | 'approved' | 'rejected' | 'expired' | 'cancelled';

/**
 * Schema for updating a payment (mainly status updates).
 */
export type PaymentUpdate = {
    status?: (PaymentStatus | null);
    external_id?: (string | null);
    source?: (PaymentSource | null);
    rate?: (number | string | null);
    currency?: (string | null);
};

export type PopupCreate = {
    tenant_id?: (string | null);
    name: string;
    slug?: string;
    start_date?: (string | null);
    end_date?: (string | null);
    status?: PopupStatus;
    allows_spouse?: (boolean | null);
    allows_children?: (boolean | null);
    allows_coupons?: (boolean | null);
    image_url?: (string | null);
    icon_url?: (string | null);
    express_checkout_background?: (string | null);
    web_url?: (string | null);
    blog_url?: (string | null);
    twitter_url?: (string | null);
    simplefi_api_key?: (string | null);
};

export type PopupPublic = {
    name: string;
    slug: string;
    tenant_id: string;
    start_date?: (string | null);
    end_date?: (string | null);
    status?: PopupStatus;
    allows_spouse?: (boolean | null);
    allows_children?: (boolean | null);
    allows_coupons?: (boolean | null);
    image_url?: (string | null);
    icon_url?: (string | null);
    express_checkout_background?: (string | null);
    web_url?: (string | null);
    blog_url?: (string | null);
    twitter_url?: (string | null);
    simplefi_api_key?: (string | null);
    id: string;
};

/**
 * Schema for adding a reviewer to a popup.
 */
export type PopupReviewerCreate = {
    user_id: string;
    is_required?: boolean;
    weight_multiplier?: number;
};

/**
 * PopupReviewer schema for API responses.
 */
export type PopupReviewerPublic = {
    id: string;
    popup_id: string;
    user_id: string;
    tenant_id: string;
    is_required: boolean;
    weight_multiplier: number;
    created_at?: (string | null);
    user_email?: (string | null);
    user_full_name?: (string | null);
};

/**
 * Schema for updating a popup reviewer.
 */
export type PopupReviewerUpdate = {
    is_required?: (boolean | null);
    weight_multiplier?: (number | null);
};

export type PopupStatus = 'draft' | 'active' | 'archived' | 'ended';

export type PopupUpdate = {
    name?: (string | null);
    slug?: (string | null);
    status?: (PopupStatus | null);
    start_date?: (string | null);
    end_date?: (string | null);
    allows_spouse?: (boolean | null);
    allows_children?: (boolean | null);
    allows_coupons?: (boolean | null);
    image_url?: (string | null);
    icon_url?: (string | null);
    express_checkout_background?: (string | null);
    web_url?: (string | null);
    blog_url?: (string | null);
    twitter_url?: (string | null);
    simplefi_api_key?: (string | null);
};

/**
 * Request to generate a presigned upload URL.
 */
export type PresignedUrlRequest = {
    /**
     * Original filename
     */
    filename: string;
    /**
     * MIME type of the file
     */
    content_type: string;
};

/**
 * Response with presigned URL for upload.
 */
export type PresignedUrlResponse = {
    /**
     * Presigned URL for PUT upload
     */
    upload_url: string;
    /**
     * Storage key for the file
     */
    key: string;
    /**
     * Public URL after upload
     */
    public_url: string;
};

/**
 * Product categories determining which fields are relevant.
 */
export type ProductCategory = 'ticket' | 'housing' | 'merch' | 'other';

/**
 * Product schema for creation.
 */
export type ProductCreate = {
    popup_id: string;
    name: string;
    slug?: (string | null);
    price: (number | string);
    compare_price?: (number | string | null);
    description?: (string | null);
    category?: ProductCategory;
    attendee_category?: (TicketAttendeeCategory | null);
    duration_type?: (TicketDuration | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: boolean;
    exclusive?: boolean;
    max_quantity?: (number | null);
};

/**
 * Product schema for API responses.
 */
export type ProductPublic = {
    tenant_id: string;
    popup_id: string;
    name: string;
    slug: string;
    price: string;
    compare_price?: (string | null);
    description?: (string | null);
    category?: ProductCategory;
    attendee_category?: (TicketAttendeeCategory | null);
    duration_type?: (TicketDuration | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: boolean;
    exclusive?: boolean;
    max_quantity?: (number | null);
    id: string;
};

/**
 * Product schema for updates.
 */
export type ProductUpdate = {
    name?: (string | null);
    slug?: (string | null);
    price?: (number | string | null);
    compare_price?: (number | string | null);
    description?: (string | null);
    category?: (ProductCategory | null);
    attendee_category?: (TicketAttendeeCategory | null);
    duration_type?: (TicketDuration | null);
    start_date?: (string | null);
    end_date?: (string | null);
    is_active?: (boolean | null);
    exclusive?: (boolean | null);
    max_quantity?: (number | null);
};

/**
 * Decision options for application reviews.
 */
export type ReviewDecision = 'strong_yes' | 'yes' | 'no' | 'strong_no';

/**
 * Summary of reviews for an application.
 */
export type ReviewSummary = {
    total_reviews: number;
    strong_yes_count: number;
    yes_count: number;
    no_count: number;
    strong_no_count: number;
    weighted_score?: (number | null);
    reviews: Array<ApplicationReviewPublic>;
};

/**
 * Card payment info from SimpleFI.
 */
export type SimpleFICardPayment = {
    provider: string;
    status: string;
    coin?: string;
};

/**
 * Data payload from SimpleFI webhook.
 */
export type SimpleFIData = {
    payment_request: SimpleFIPaymentRequest;
    new_payment?: (SimpleFIPaymentInfo | SimpleFICardPayment | null);
};

/**
 * Payment info from SimpleFI.
 */
export type SimpleFIPaymentInfo = {
    coin: string;
    hash: string;
    amount: number;
    paid_at: string;
};

/**
 * Payment request details from SimpleFI.
 */
export type SimpleFIPaymentRequest = {
    id: string;
    order_id: number;
    amount: number;
    amount_paid: number;
    currency: string;
    reference: {
        [key: string]: unknown;
    };
    status: string;
    status_detail: string;
    transactions: Array<SimpleFITransaction>;
    card_payment?: (SimpleFICardPayment | null);
    payments: Array<SimpleFIPaymentInfo>;
};

/**
 * Price details for a SimpleFI transaction.
 */
export type SimpleFIPriceDetails = {
    currency: string;
    final_amount: number;
    rate: number;
};

/**
 * Transaction details from SimpleFI.
 */
export type SimpleFITransaction = {
    id: string;
    coin: string;
    chain_id: number;
    status: string;
    price_details: SimpleFIPriceDetails;
};

/**
 * SimpleFI webhook payload schema.
 */
export type SimpleFIWebhookPayload = {
    id: string;
    event_type: string;
    entity_type: string;
    entity_id: string;
    data: SimpleFIData;
};

export type TenantCreate = {
    name: string;
    slug?: string;
    sender_email?: (string | null);
    sender_name?: (string | null);
    image_url?: (string | null);
    icon_url?: (string | null);
};

export type TenantCredentialResponse = {
    credentials: Array<CredentialInfo>;
    db_host: string;
    db_port: number;
    db_name: string;
};

export type TenantPublic = {
    name: string;
    slug: string;
    deleted?: boolean;
    sender_email?: (string | null);
    sender_name?: (string | null);
    image_url?: (string | null);
    icon_url?: (string | null);
    id: string;
};

export type TenantUpdate = {
    name?: (string | null);
    slug?: (string | null);
    sender_email?: (string | null);
    sender_name?: (string | null);
    image_url?: (string | null);
    icon_url?: (string | null);
};

/**
 * Attendee categories for ticket products.
 */
export type TicketAttendeeCategory = 'main' | 'spouse' | 'kid';

/**
 * Duration types for ticket products.
 */
export type TicketDuration = 'day' | 'week' | 'month' | 'full';

/**
 * Minimal product data for tickets.
 */
export type TicketProduct = {
    name: string;
    category?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    quantity?: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Request to login a user.
 */
export type UserAuth = {
    email: string;
};

export type UserCreate = {
    email: string;
    full_name?: (string | null);
    role: UserRole;
    deleted?: boolean;
    tenant_id?: (string | null);
    auth_code?: (string | null);
    code_expiration?: (string | null);
    auth_attempts?: number;
};

export type UserPublic = {
    email: string;
    full_name?: (string | null);
    role: UserRole;
    deleted?: boolean;
    tenant_id?: (string | null);
    auth_code?: (string | null);
    code_expiration?: (string | null);
    auth_attempts?: number;
    id: string;
};

export type UserRole = 'superadmin' | 'admin' | 'viewer';

/**
 * Statuses that users can set (subset of ApplicationStatus).
 */
export type UserSettableStatus = 'draft' | 'in review';

export type UserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
    role?: (UserRole | null);
};

/**
 * Request to authenticate a user.
 */
export type UserVerify = {
    email: string;
    code: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ApplicationReviewsListReviewsData = {
    applicationId: string;
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type ApplicationReviewsListReviewsResponse = (ListModel_ApplicationReviewPublic_);

export type ApplicationReviewsSubmitReviewData = {
    applicationId: string;
    requestBody: ApplicationReviewCreate;
    xTenantId?: (string | null);
};

export type ApplicationReviewsSubmitReviewResponse = (ApplicationReviewPublic);

export type ApplicationReviewsGetReviewSummaryData = {
    applicationId: string;
    xTenantId?: (string | null);
};

export type ApplicationReviewsGetReviewSummaryResponse = (ReviewSummary);

export type ApplicationReviewsListPendingReviewsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type ApplicationReviewsListPendingReviewsResponse = (ListModel);

export type ApplicationReviewsListMyReviewsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type ApplicationReviewsListMyReviewsResponse = (ListModel_ApplicationReviewPublic_);

export type ApplicationsListApplicationsData = {
    humanId?: (string | null);
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    statusFilter?: (ApplicationStatus | null);
    xTenantId?: (string | null);
};

export type ApplicationsListApplicationsResponse = (ListModel_ApplicationPublic_);

export type ApplicationsCreateApplicationAdminData = {
    requestBody: ApplicationAdminCreate;
    xTenantId?: (string | null);
};

export type ApplicationsCreateApplicationAdminResponse = (ApplicationPublic);

export type ApplicationsGetApplicationData = {
    applicationId: string;
    xTenantId?: (string | null);
};

export type ApplicationsGetApplicationResponse = (ApplicationPublic);

export type ApplicationsUpdateApplicationAdminData = {
    applicationId: string;
    requestBody: ApplicationAdminUpdate;
    xTenantId?: (string | null);
};

export type ApplicationsUpdateApplicationAdminResponse = (ApplicationPublic);

export type ApplicationsDeleteApplicationData = {
    applicationId: string;
    xTenantId?: (string | null);
};

export type ApplicationsDeleteApplicationResponse = (void);

export type ApplicationsListMyApplicationsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
};

export type ApplicationsListMyApplicationsResponse = (ListModel_ApplicationPublic_);

export type ApplicationsListMyTicketsResponse = (Array<AttendeeWithTickets>);

export type ApplicationsGetMyApplicationData = {
    popupId: string;
};

export type ApplicationsGetMyApplicationResponse = (ApplicationPublic);

export type ApplicationsUpdateMyApplicationData = {
    popupId: string;
    requestBody: ApplicationUpdate;
};

export type ApplicationsUpdateMyApplicationResponse = (ApplicationPublic);

export type ApplicationsCreateMyApplicationData = {
    requestBody: ApplicationCreate;
};

export type ApplicationsCreateMyApplicationResponse = (ApplicationPublic);

export type ApplicationsAddMyAttendeeData = {
    popupId: string;
    requestBody: AttendeeCreate;
};

export type ApplicationsAddMyAttendeeResponse = (ApplicationPublic);

export type ApplicationsUpdateMyAttendeeData = {
    attendeeId: string;
    popupId: string;
    requestBody: AttendeeUpdate;
};

export type ApplicationsUpdateMyAttendeeResponse = (ApplicationPublic);

export type ApplicationsDeleteMyAttendeeData = {
    attendeeId: string;
    popupId: string;
};

export type ApplicationsDeleteMyAttendeeResponse = (ApplicationPublic);

export type ApprovalStrategiesGetApprovalStrategyData = {
    popupId: string;
    xTenantId?: (string | null);
};

export type ApprovalStrategiesGetApprovalStrategyResponse = (ApprovalStrategyPublic);

export type ApprovalStrategiesCreateOrUpdateApprovalStrategyData = {
    popupId: string;
    requestBody: ApprovalStrategyCreate;
    xTenantId?: (string | null);
};

export type ApprovalStrategiesCreateOrUpdateApprovalStrategyResponse = (ApprovalStrategyPublic);

export type ApprovalStrategiesUpdateApprovalStrategyData = {
    popupId: string;
    requestBody: ApprovalStrategyUpdate;
    xTenantId?: (string | null);
};

export type ApprovalStrategiesUpdateApprovalStrategyResponse = (ApprovalStrategyPublic);

export type ApprovalStrategiesDeleteApprovalStrategyData = {
    popupId: string;
    xTenantId?: (string | null);
};

export type ApprovalStrategiesDeleteApprovalStrategyResponse = (void);

export type AttendeesListAttendeesData = {
    applicationId?: (string | null);
    email?: (string | null);
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type AttendeesListAttendeesResponse = (ListModel_AttendeePublic_);

export type AttendeesGetAttendeeData = {
    attendeeId: string;
    xTenantId?: (string | null);
};

export type AttendeesGetAttendeeResponse = (AttendeePublic);

export type AttendeesUpdateAttendeeData = {
    attendeeId: string;
    requestBody: AttendeeUpdate;
    xTenantId?: (string | null);
};

export type AttendeesUpdateAttendeeResponse = (AttendeePublic);

export type AttendeesDeleteAttendeeData = {
    attendeeId: string;
    xTenantId?: (string | null);
};

export type AttendeesDeleteAttendeeResponse = (void);

export type AttendeesGetByCheckInCodeData = {
    code: string;
    xTenantId?: (string | null);
};

export type AttendeesGetByCheckInCodeResponse = (AttendeePublic);

export type AttendeesGetTicketsByEmailData = {
    email: string;
    xTenantId?: (string | null);
};

export type AttendeesGetTicketsByEmailResponse = (Array<AttendeeWithTickets>);

export type AuthUserLoginData = {
    requestBody: UserAuth;
};

export type AuthUserLoginResponse = (AuthCodeSentResponse);

export type AuthUserAuthenticateData = {
    requestBody: UserVerify;
};

export type AuthUserAuthenticateResponse = (Token);

export type AuthHumanLoginData = {
    requestBody: HumanAuth;
};

export type AuthHumanLoginResponse = (AuthCodeSentResponse);

export type AuthHumanAuthenticateData = {
    requestBody: HumanVerify;
};

export type AuthHumanAuthenticateResponse = (Token);

export type CouponsListCouponsData = {
    isActive?: (boolean | null);
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type CouponsListCouponsResponse = (ListModel_CouponPublic_);

export type CouponsCreateCouponData = {
    requestBody: CouponCreate;
    xTenantId?: (string | null);
};

export type CouponsCreateCouponResponse = (CouponPublic);

export type CouponsGetCouponData = {
    couponId: string;
    xTenantId?: (string | null);
};

export type CouponsGetCouponResponse = (CouponPublic);

export type CouponsUpdateCouponData = {
    couponId: string;
    requestBody: CouponUpdate;
    xTenantId?: (string | null);
};

export type CouponsUpdateCouponResponse = (CouponPublic);

export type CouponsDeleteCouponData = {
    couponId: string;
    xTenantId?: (string | null);
};

export type CouponsDeleteCouponResponse = (void);

export type CouponsValidateCouponData = {
    requestBody: CouponValidate;
};

export type CouponsValidateCouponResponse = (CouponPublic);

export type DashboardGetDashboardStatsData = {
    /**
     * Popup ID to get stats for
     */
    popupId: string;
    xTenantId?: (string | null);
};

export type DashboardGetDashboardStatsResponse = (DashboardStats);

export type FormFieldsListFormFieldsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type FormFieldsListFormFieldsResponse = (ListModel_FormFieldPublic_);

export type FormFieldsCreateFormFieldData = {
    requestBody: FormFieldCreate;
    xTenantId?: (string | null);
};

export type FormFieldsCreateFormFieldResponse = (FormFieldPublic);

export type FormFieldsGetFormFieldData = {
    fieldId: string;
    xTenantId?: (string | null);
};

export type FormFieldsGetFormFieldResponse = (FormFieldPublic);

export type FormFieldsUpdateFormFieldData = {
    fieldId: string;
    requestBody: FormFieldUpdate;
    xTenantId?: (string | null);
};

export type FormFieldsUpdateFormFieldResponse = (FormFieldPublic);

export type FormFieldsDeleteFormFieldData = {
    fieldId: string;
    xTenantId?: (string | null);
};

export type FormFieldsDeleteFormFieldResponse = (void);

export type FormFieldsGetApplicationSchemaData = {
    popupId: string;
    xTenantId?: (string | null);
};

export type FormFieldsGetApplicationSchemaResponse = ({
    [key: string]: unknown;
});

export type GroupsListGroupsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type GroupsListGroupsResponse = (ListModel_GroupPublic_);

export type GroupsCreateGroupData = {
    requestBody: GroupCreate;
    xTenantId?: (string | null);
};

export type GroupsCreateGroupResponse = (GroupPublic);

export type GroupsGetGroupData = {
    groupId: string;
    xTenantId?: (string | null);
};

export type GroupsGetGroupResponse = (GroupWithMembers);

export type GroupsUpdateGroupData = {
    groupId: string;
    requestBody: GroupAdminUpdate;
    xTenantId?: (string | null);
};

export type GroupsUpdateGroupResponse = (GroupPublic);

export type GroupsDeleteGroupData = {
    groupId: string;
    xTenantId?: (string | null);
};

export type GroupsDeleteGroupResponse = (void);

export type GroupsListMyGroupsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
};

export type GroupsListMyGroupsResponse = (ListModel_GroupPublic_);

export type GroupsGetMyGroupData = {
    groupId: string;
};

export type GroupsGetMyGroupResponse = (GroupWithMembers);

export type GroupsUpdateMyGroupData = {
    groupId: string;
    requestBody: GroupUpdate;
};

export type GroupsUpdateMyGroupResponse = (GroupPublic);

export type GroupsAddGroupMemberData = {
    groupId: string;
    requestBody: GroupMemberCreate;
};

export type GroupsAddGroupMemberResponse = (GroupMemberPublic);

export type GroupsAddGroupMembersBatchData = {
    groupId: string;
    requestBody: GroupMemberBatch;
};

export type GroupsAddGroupMembersBatchResponse = (Array<GroupMemberBatchResult>);

export type GroupsUpdateGroupMemberData = {
    groupId: string;
    humanId: string;
    requestBody: GroupMemberUpdate;
};

export type GroupsUpdateGroupMemberResponse = (GroupMemberPublic);

export type GroupsRemoveGroupMemberData = {
    groupId: string;
    humanId: string;
};

export type GroupsRemoveGroupMemberResponse = (void);

export type GroupsGetGroupPublicData = {
    groupSlug: string;
};

export type GroupsGetGroupPublicResponse = (GroupPublic);

export type HumansListHumansData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type HumansListHumansResponse = (ListModel_HumanPublic_);

export type HumansCreateHumanData = {
    requestBody: HumanCreate;
    xTenantId?: (string | null);
};

export type HumansCreateHumanResponse = (HumanPublic);

export type HumansGetCurrentHumanInfoResponse = (HumanPublic);

export type HumansGetHumanData = {
    humanId: string;
    xTenantId?: (string | null);
};

export type HumansGetHumanResponse = (HumanPublic);

export type HumansUpdateHumanData = {
    humanId: string;
    requestBody: HumanUpdate;
    xTenantId?: (string | null);
};

export type HumansUpdateHumanResponse = (HumanPublic);

export type PaymentsListPaymentsData = {
    applicationId?: (string | null);
    externalId?: (string | null);
    /**
     * Maximum number of items to return
     */
    limit?: number;
    paymentStatus?: (PaymentStatus | null);
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type PaymentsListPaymentsResponse = (ListModel_PaymentPublic_);

export type PaymentsGetPaymentData = {
    paymentId: string;
    xTenantId?: (string | null);
};

export type PaymentsGetPaymentResponse = (PaymentPublic);

export type PaymentsUpdatePaymentData = {
    paymentId: string;
    requestBody: PaymentUpdate;
    xTenantId?: (string | null);
};

export type PaymentsUpdatePaymentResponse = (PaymentPublic);

export type PaymentsApprovePaymentData = {
    paymentId: string;
    xTenantId?: (string | null);
};

export type PaymentsApprovePaymentResponse = (PaymentPublic);

export type PaymentsListMyPaymentsData = {
    applicationId: string;
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
};

export type PaymentsListMyPaymentsResponse = (ListModel_PaymentPublic_);

export type PaymentsPreviewMyPaymentData = {
    requestBody: PaymentCreate;
};

export type PaymentsPreviewMyPaymentResponse = (PaymentPreview);

export type PaymentsCreateMyPaymentData = {
    requestBody: PaymentCreate;
};

export type PaymentsCreateMyPaymentResponse = ((PaymentPublic | PaymentPreview));

export type PaymentsSimplefiWebhookData = {
    requestBody: SimpleFIWebhookPayload;
};

export type PaymentsSimplefiWebhookResponse = ({
    [key: string]: unknown;
});

export type PopupReviewersListReviewersData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId: string;
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type PopupReviewersListReviewersResponse = (ListModel_PopupReviewerPublic_);

export type PopupReviewersAddReviewerData = {
    popupId: string;
    requestBody: PopupReviewerCreate;
    xTenantId?: (string | null);
};

export type PopupReviewersAddReviewerResponse = (PopupReviewerPublic);

export type PopupReviewersUpdateReviewerData = {
    popupId: string;
    requestBody: PopupReviewerUpdate;
    userId: string;
    xTenantId?: (string | null);
};

export type PopupReviewersUpdateReviewerResponse = (PopupReviewerPublic);

export type PopupReviewersRemoveReviewerData = {
    popupId: string;
    userId: string;
    xTenantId?: (string | null);
};

export type PopupReviewersRemoveReviewerResponse = (void);

export type PopupsListPopupsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type PopupsListPopupsResponse = (ListModel_PopupPublic_);

export type PopupsCreatePopupData = {
    requestBody: PopupCreate;
    xTenantId?: (string | null);
};

export type PopupsCreatePopupResponse = (PopupPublic);

export type PopupsGetPopupData = {
    popupId: string;
    xTenantId?: (string | null);
};

export type PopupsGetPopupResponse = (PopupPublic);

export type PopupsUpdatePopupData = {
    popupId: string;
    requestBody: PopupUpdate;
    xTenantId?: (string | null);
};

export type PopupsUpdatePopupResponse = (PopupPublic);

export type PopupsDeletePopupData = {
    popupId: string;
    xTenantId?: (string | null);
};

export type PopupsDeletePopupResponse = (void);

export type ProductsListProductsData = {
    category?: (ProductCategory | null);
    isActive?: (boolean | null);
    /**
     * Maximum number of items to return
     */
    limit?: number;
    popupId?: (string | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    xTenantId?: (string | null);
};

export type ProductsListProductsResponse = (ListModel_ProductPublic_);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
    xTenantId?: (string | null);
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsGetProductData = {
    productId: string;
    xTenantId?: (string | null);
};

export type ProductsGetProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
    xTenantId?: (string | null);
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    productId: string;
    xTenantId?: (string | null);
};

export type ProductsDeleteProductResponse = (void);

export type TenantsListTenantsData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    /**
     * Number of items to skip
     */
    skip?: number;
};

export type TenantsListTenantsResponse = (ListModel_TenantPublic_);

export type TenantsCreateTenantData = {
    requestBody: TenantCreate;
};

export type TenantsCreateTenantResponse = (TenantPublic);

export type TenantsGetTenantData = {
    tenantId: string;
};

export type TenantsGetTenantResponse = (TenantPublic);

export type TenantsUpdateTenantData = {
    requestBody: TenantUpdate;
    tenantId: string;
};

export type TenantsUpdateTenantResponse = (TenantPublic);

export type TenantsDeleteTenantData = {
    tenantId: string;
};

export type TenantsDeleteTenantResponse = (void);

export type TenantsGetCredentialsData = {
    tenantId: string;
};

export type TenantsGetCredentialsResponse = (TenantCredentialResponse);

export type TenantsDeleteCredentialsData = {
    tenantId: string;
};

export type TenantsDeleteCredentialsResponse = (void);

export type UploadsGetPresignedUploadUrlData = {
    requestBody: PresignedUrlRequest;
};

export type UploadsGetPresignedUploadUrlResponse = (PresignedUrlResponse);

export type UsersListUsersData = {
    /**
     * Maximum number of items to return
     */
    limit?: number;
    role?: (UserRole | null);
    /**
     * Number of items to skip
     */
    skip?: number;
    tenantId?: (string | null);
};

export type UsersListUsersResponse = (ListModel_UserPublic_);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersGetCurrentUserInfoResponse = (UserPublic);

export type UsersGetUserData = {
    userId: string;
};

export type UsersGetUserResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (void);