export {
  clearHousing,
  computeNights,
  emptySelection,
  hasAnySelection,
  type HousingInput,
  type HousingSelection,
  selectHousing,
  type SelectionState,
  setCoupon,
  setHousingQuantity,
  setInsurance,
  setQuantity,
  toggleProduct,
  totalSelectedQuantity,
} from "./state"
