"""Update schemas

Revision ID: 086f8872b3fb
Revises: bc63778bf65f
Create Date: 2026-02-27 12:26:13.767291

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '086f8872b3fb'
down_revision = 'bc63778bf65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popups', sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('popups', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_url')
    op.drop_column('popups', 'location')
    op.drop_column('popups', 'tagline')
    # ### end Alembic commands ###
