"""Drop global unique index on groups.slug

Revision ID: bc63778bf65f
Revises: 0011_abandoned_cart
Create Date: 2026-02-24 14:08:25.948711

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc63778bf65f'
down_revision = '0011_abandoned_cart'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    # ### end Alembic commands ###
